confluentinc/common-docker

Jenkinsfile
README.md
base/Dockerfile
base/README.md
base/foo
base/pom.xml
base/requirements.txt
base/setup.py
base/test/test_base_image.py
base/tox.ini
pom.xml
utility-belt/README.md
utility-belt/checkstyle/suppressions.xml
utility-belt/pom.xml
utility-belt/src/main/java/io/confluent/admin/utils/ClusterStatus.java
utility-belt/src/main/java/io/confluent/admin/utils/TopicEnsure.java
utility-belt/src/main/java/io/confluent/admin/utils/TopicSpec.java
utility-belt/src/main/java/io/confluent/admin/utils/ZookeeperConnectionWatcher.java
utility-belt/src/main/java/io/confluent/admin/utils/cli/KafkaReadyCommand.java
utility-belt/src/main/java/io/confluent/admin/utils/cli/TopicEnsureCommand.java
utility-belt/src/main/java/io/confluent/admin/utils/cli/ZookeeperReadyCommand.java
utility-belt/src/test/bin/cli-test.sh
utility-belt/src/test/java/io/confluent/admin/utils/ClusterStatusSASLTest.java
utility-belt/src/test/java/io/confluent/admin/utils/ClusterStatusTest.java
utility-belt/src/test/java/io/confluent/admin/utils/ClusterWaitTest.java
utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java
utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedZookeeperEnsemble.java

This will let us build confluentinc/common without depending on Kafka.

Extract utility-belt and base from confluentinc/common@cd2a5a2

---

utility-belt/pom.xml

- This should get inherited from the common pom
- Related PR: confluentinc/common#212

Remove jackson databind version override

---

base/README.md

I am updating the readme document to include information about building images using different os types. I also cleaned up some minor things.

ST-2560: Updating readme.

---

base/Dockerfile.rhel8

This creates a user "appuser" that will then be used to run all the services in all of our images instead of running as the root user.
I tested these changes by building all the images and running cp-demo.

ST-2560: Run as appuser in rhel base image

---

CONTRIBUTING.md

ST-3638: Adding contributing guide line from cp-docker-images repo

---

base/Dockerfile
base/requirements.txt

duplicate of #91 but to a different branch

ST-3962: update confluent-docker-utils to latest

---

base/Dockerfile.ubi8

We want to consume the changes from https://github.com/confluentinc/confluent-docker-utils/pull/31 here now.

Use confluent-docker-utils 0.0.43

---

utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedZookeeperEnsemble.java

This reverts commit 76420e591f099a2981daf7c43da218b7046f1bb9.

Revert "Fix compilation with zookeeper 3.5.5 (#36)"

---

pom.xml

See: https://catalog.redhat.com/software/containers/ubi8-minimal/5c64772edd19c77a158ea216?tag=8.4-200

sec: Update UBI base image to 8.4-200.1622548483

---

base/Dockerfile.ubi8
pom.xml

- Pin to 11.0.12
- Only install headless JRE and JDK to reduce image size

MINOR: Pin Zulu OpenJDK JRE/JDK Headless to 11.0.12

---

base/Dockerfile

- Install "newer" Repo Channel
- Install headless JVMs.
- Pin/ensure version 8.0.302 is installed

MINOR: Pin Zulu OpenJDK JRE/JDK Headless to 8.0.302

---

Jenkinsfile

Disable concurrent builds 54x

---

pom.xml

Update image revision to 8.5-230.1645809059, needed for 7.1 RCs

build: Update base image to 8.5-230.1645809059

---

Jenkinsfile

To be merged to 7.0.x and pint merged up to master

feat: Enable arm64 builds for 7.0+

---

base/pom.xml
utility-belt/pom.xml

Description:
Merge 8b22f88c735be5494a43402ef1987aad57404d28 from 7.2.x into master
JIRA ticket: DP-7573

Migrate log4j to reload4j (#197)

---

pom.xml

Update to 8.6-902.1661794353 based on latest version [here](https://hub.docker.com/r/redhat/ubi8-minimal/tags)
To be merged up through master

[chore] Update base image version

---

pom.xml

Update ubi8 version from 8.6-854 to 8.6-941 and zulu-openjdk from 11.0.15-1 to 11.0.16-1

[DP-9351] update versions to resolve common-docker build error

---

base/Dockerfile.ubi8
pom.xml

To be pint merged through master

Update base image version to 8.7-1049

---

utility-belt/pom.xml

Problem: 
utility-belt has test failures.

fix: utility-belt test fixes

---

pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 5.5.x to 6.0.x)

---

pom.xml
utility-belt/pom.xml

Unpin SnakeYaml to pull the update version from common. see https://github.com/confluentinc/common/pull/514

APPSEC-2550: Unpin SnakeYaml to import current version from common

---

.github/pull_request_template.md

This changes the pull_request_template.md to be much simpler than it is currently. The current template is overly complicated and many people do not fill it out before creating pull requests. The hope is that this new streamlined template will result in people filling in the PR description.
Copied the template contents into this PR description and used it for writing this description.

DP-11448: add/update pull_request_template.md

---

utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java

Removing dependency on MockTime
Jenkins node not available to run the PR tests.
Built done on local is successful

CPBR-99: fixing MockTime import

---

pom.xml

CPBR-209: updating python 3.9 version

---

utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java

Fix compilation error in EmbeddedKafkaCluster

---

Jenkinsfile

CPBR-93: updating slack channel

---

base/README.md

@gracechensd same commit as before but we need in `-post` branches instead of just `-.x`

add license section to cp-base-new README

---

base-lite/README.md

Add license section to base-lite image
n/a

add license section to cp-base-lite README

---

pom.xml

Several CVEs have been addressed in docker-utils: 
https://github.com/confluentinc/confluent-docker-utils/pull/61
we need to update docker utils to bring in the updated versions to base-docker image

update version of docker-utils

---

pom.xml

Updating python dependencies to resolve CVE: CVE-2022-40897

DP-xyz: update pythontools

---

pom.xml

adding the version definition that was errornously removed, update version to address another CVE in python cryptography

re-add docker-utils and update version

---

.github/CODEOWNERS

Update CODEOWNERS to cp-build-and-release-team

Update CODEOWNERS to cp-build-and-release-team

---

pom.xml

This is a sample PR only to run PR jobs to debug an ongoing bug

CPF-239: Change golang base image to fix job failure

---

pom.xml

Update the confluent-docker-utils to include the fix for cryptography package
see:
https://github.com/confluentinc/confluent-docker-utils/pull/64

update confluent-docker-utils to include fix for cryptography package

---

pom.xml

Bump up zulu openjdk version

---

pom.xml

* Bump up zulu openjdk version
* Bump up python39 version

Bump up zulu openjdk and python39 version (#335)

---

pom.xml

Bump up packages versions

---

utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedZookeeperEnsemble.java

Cherry-pick of 93b79d0c2e9a81 to 6.1.x

QuorumPeer Changes for Zookeeper 3.6

---

pom.xml

CPBR-682: Fixing dependencies for IB repos
(cherry picked from commit c00cf45298e6db86b3cbb069a5f8bd68f7ad3cf4)

CPBR-682: Merge pull request #345 from confluentinc/7.2.8-ib-dependencies-update

---

pom.xml

Updating ubi8 image tag to latest version

CPBR-851: Updating ubi8 image version to 8.9-1029

---

base/Dockerfile.ubi8
pom.xml

Adding FIPS flag in common docker. Removing all files with setuid/setgid flag set in cp-base-new image.
Locally Built the image.

CPBR-994: removing setuid and setgid bit

---

base/Dockerfile.ubi8

Reverts confluentinc/common-docker#355

 CPBR-994: "Revert removing setuid and setgid bit"

---

pom.xml

Update confluent-docker-utils to address [CVE-2024-22195](https://confluentinc.atlassian.net/browse/CVE-2024-22195)

APPSEC-3618: update confluent-docker-utils

---

base/Dockerfile.ubi8
base/pom.xml
pom.xml

Removing setuid/setgid bits in cp-base-new image
PRs run on jenkins for validation

CPBR-994: adding fedramp changes

---

pom.xml

Update ubi-8 image version to 8.9-1108.1705420507

Update ubi-8 image version to 8.9-1108.1705420507

---

pom.xml

Increase the version tag of the ubi8 minimal image.
Change in file: pom.xml

CONMON-824 Cherry pick ubi-8 image update

---

service.yml

Enable semaphore in service.yml

Onboard repo to semaphore

---

pom.xml

Update ubi8 version

---

service.yml

Install tox using pip
OS type added
maven specific args added

Add ubi8 OS type

---

pom.xml

CPBR-1051 | Bump up zulu openjdk version to 11.0.22

---

pom.xml

update docker utils to address CVE-2023-50782

APPSEC-3729: update confluent-docker-utils

---

base/Dockerfile.ubi8

adding kafka on cub classpath

---

.semaphore/semaphore.yml
base/requirements.txt

Set python version 3.9
Update confluent-docker-utils version for cp-base images

Set python version 3.9

---

pom.xml

CVE fixes - version bump zulu jdk, ubi8, confluent-docker-utils

---

pom.xml

Update confluent-docker-utils to fix the regression introduced with the migration of confluent-docker-utils to semaphore.

DP-13846: update confluent-docker-utils

---

.semaphore/semaphore.yml
pom.xml
service.yml

https://semaphore.ci.confluent.io/workflows/1ff990e4-a402-427e-93b9-13b870df5edc?pipeline_id=a9e399a7-fb89-402e-93e2-6cd21cd443cb

CPBR-677: MIgrate common-docker to semaphore

---

pom.xml

CPBR-1115 Update glibc version

---

pom.xml

Use updated common-docker-util version, pending https://github.com/confluentinc/confluent-docker-utils/pull/80
Existing tests

APPSEC-3786: Update confluent-docker-utils

---

base/pom.xml

Cherry pick arm64 support

---

service.yml

Enable semaphore to push the latest image. 
Change will be PR tested.

minor: enable semaphore push latest

---

.semaphore/semaphore.yml

fix semaphore workflow

---

service.yml

Would like to enable these parameters to get the changes in developement. Using this project as a testing ground.
The templates have unittest. Integrating with this project is for further testing.

minor: add use_packages and cp_images

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml
service.yml

Testing tasks. Removed pushes that may conflict with the current build. Build only pushes packaging tag. Promotion takes packaging tag and retags (push has been removed for promotions)

feat: testing new cp_dockerfile templates

---

pom.xml

update ubi8 minimal image version to the latest one `8.9-1137`

update ubi8 minimal image version

---

.semaphore/cp_dockerfile_build.yml
service.yml

minor: fix task

---

.semaphore/cp_dockerfile_build.yml

Remove overwrite maven config file. (This was moved)

minor: fix task maven overwrite

---

pom.xml

Builds are failing with: 
```
[INFO] Error: Unable to find a match: curl-7.61.1-33.el8 libcurl-7.61.1-33.el8
```
CI build

minor: update curl version

---

pom.xml

Ubi8 image update:
Build failed with:
[INFO] Error: Unable to find a match: curl-7.61.1-33.el8 libcurl-7.61.1-33.el8

curl fix and ubi8-update

---

.semaphore/cp_dockerfile_build.yml

minor: task fix prod image name

---

.semaphore/cp_dockerfile_build.yml

minor: fix task build push

---

.semaphore/cp_dockerfile_promote.yml

minor: fix promote task syntax

---

.semaphore/cp_dockerfile_promote.yml

Docker has `--rm` instead of `-rm`

minor: fix docker run in promote task

---

.semaphore/cp_dockerfile_promote.yml

Reverts confluentinc/common-docker#432
also add docker login

Revert "minor: fix manifest create promotion task"

---

pom.xml

Ubi8 image update:
Build failed with:
[INFO] Error: Unable to find a match: curl-7.61.1-33.el8 libcurl-7.61.1-33.el8

Curl fix and update ubi8 image

---

pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 7.6.x to 7.7.x)

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml
service.yml

Added semaphore config files for migration
https://semaphore.ci.confluent.io/jobs/bb3be444-7349-4b5b-942c-290062872e8a

semaphore migration for 6.2.x

---

.semaphore/cp_dockerfile_build.yml

Update python version and dev registry

---

pom.xml

(cherry picked from commit 2d1c023dd873f62957e0cecb61a49b425ea46078)
Fixing post branch for IronBank releases

CPBR-1262: Curl fix and update ubi8 image (#434) (#436)

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml

7.0.x - migrate to semaphore

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml

7.1.x - migrate to semaphore

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml

7.2.x - migrate to semaphore

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml

7.4.x - migrate to semaphore

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml

7.3.x - migrate to semaphore

---

.semaphore/cp_dockerfile_build.yml
service.yml

6.2.x - Added image signing

---

pom.xml

update confluent-docker-utils to address vulnerability in python library idna

update confluent-docker-utils 

---

.semaphore/cp_dockerfile_build.yml
.semaphore/semaphore.yml

added image signing and packaging build numbers fix

sign images

---

base-lite/Dockerfile.ubi8
base/Dockerfile.ubi8
pom.xml

CPBR-726 added java17 support

---

jmxterm/Dockerfile.ubi8

Update confluent-packaging-tools ref

---

pom.xml

CPBR-1432 Update ubi8-minimal to latest version

---

base/requirements.txt

update docker-utils version

---

pom.xml

update lib versions

---

pom.xml

Update confluent-docker-utils to address CVE in requests python library

updated confluent-docker-utils

---

service.yml

added service.yml config file

---

.semaphore/cp_dockerfile_build.yml
pom.xml
service.yml

Making it inline with jenkins config https://github.com/confluentinc/common-docker/blob/7.0.x/Jenkinsfile#L9

CPBR-677 Fix mvn skip deploy and python version bump

---

pom.xml

updated ubi8 to latest version

update ubi8 image version

---

base/requirements.txt
pom.xml

Fixes CVEs mentioned in https://confluentinc.atlassian.net/browse/CFK-3133 related to requests library which is updated to 2.32.2 in v0.0.82 of confluent-docker-utils
https://semaphore.ci.confluent.io/workflows/419d880c-3625-46f3-b79e-c23dacfd2d08?pipeline_id=a5fae90f-60c0-41d9-b7e0-18b29282cd60

Update confluent-docker-utils version

---

base/requirements.txt
pom.xml

Fixes CVEs mentioned in https://confluentinc.atlassian.net/browse/CFK-3133 related to requests library which is updated to 2.32.2 in v0.0.82 of confluent-docker-utils
Change Description](https://semaphore.ci.confluent.io/workflows/419d880c-3625-46f3-b79e-c23dacfd2d08?pipeline_id=a5fae90f-60c0-41d9-b7e0-18b29282cd60)

Update confluent docker utils and java17

---

pom.xml

updating java17 version for CVE fix
PR build passed on 7.7.x
https://semaphore.ci.confluent.io/workflows/ae976d1d-331a-4260-a09c-98d128c1c486?pipeline_id=c4f90f04-d8e3-41b5-aa0c-c273f6b47abe

Update zulu-jdk version

---

pom.xml

Update setuptools
Update setuptools to remediate CVE

APPSEC-4420: update setuptools

---

pom.xml

update setuptools in the base container

APPSEC-4402: update setuptools

---

pom.xml
utility-belt/pom.xml

* Revert "remove definition of bouncycastle and allow mvn bring unpinned version (#3)"
* upgrade bouncycastle to 18

Add bouncycastle dependency (#5)

---

.semaphore/cp_dockerfile_build.yml
.semaphore/semaphore.yml
service.yml
sonar-project.properties

same as https://github.com/confluentinc/airlock-common-docker/pull/1

CPBR-1660: Fix python version reset by servicebot 

---

.semaphore/cp_dockerfile_build.yml
.semaphore/semaphore.yml
base-lite/Dockerfile.ubi8
base-lite/pom.xml
base/Dockerfile.ubi8
base/pom.xml
pom.xml

using temurin 17 jdk from 7.8.x onwards

CPBR-1716: using temurin 17 jdk from 7.8.x onwards

---

pom.xml

common-docker failing across branches due to glibc version

upgrade glibc

---

pom.xml

update base image for minor release

Update ubi8 base image

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml

* chore: update repo semaphore config
* chore: update repo semaphore task
* chore: update repo semaphore task
* change upstream reg
* set python version

Servicebot changes (#35)

---

pom.xml

This PR is for merge conflict resolution from 7.3.x to 7.4.x via airflow workflow.

Merge conflict resolution from 7.3.x to 7.4.x

---

pom.xml

Update ubi8-minimal to 8.10-1086

Update ubi8-minimal to latest version 

---

pom.xml

Updating pinned versions of packages for IronBank pipelines

CPBR-1877: updating pinned dependencies for cp base new

---

pom.xml

(cherry picked from commit ab209173d67003c8699f8a887e6df1cfabeb16cb)

CPBR-1877: updating pinned dependencies for cp base new 7.2.12

---

pom.xml

(cherry picked from commit ab209173d67003c8699f8a887e6df1cfabeb16cb)

CPBR-1877: updating pinned dependencies for cp base new for 7.3.10 

---

pom.xml

CPBR-1845 update golang version

---

base/requirements.txt
pom.xml

This PR is a Merge Conflict Resolution (from 7.3.x to 7.4.x). PR had to be raised to adhere to the new airlock workflow.
PR checks.

Merge Conflict Resolution (from 7.3.x to 7.4.x)

---

pom.xml

This PR will update python39 version to fix nightly and RC.

Update python39 version to fix nightly and RC

---

pom.xml

Resolve merge conflict (from 7-6-x to 7-7-x)

---

pom.xml

update python and krb5 versions

---

pom.xml

Merge conflict resolution from 7.7.x to 7.8.x
PR checks

Merge conflict resolution from 7.7.x to 7.8.x

---

pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 7.7.x to 7.8.x)

---

utility-belt/src/main/java/io/confluent/admin/utils/TopicEnsure.java

kafka has made method changes in DescribeTopicsResult class. This PR makes the corresponding changes in utility belt tests also.
Tested using cp jar build with custom components

CPBR-2142: using new method to get topic names

---

base/requirements.txt
pom.xml

updating confluent-docker-utils version in requirements for 7.7.0-cp6

---

base/requirements.txt
pom.xml

fixes CVE-2024-56201 , CVE-2024-56326

CPBR-2191 Update docker utils

---

base-java/Dockerfile.ubi8
base-java/README.md
base-java/include/etc/confluent/docker/bash-config
base-java/include/etc/confluent/docker/mesos-setup.sh
base-java/include/etc/cp-base-java/log4j.properties
base-java/license.txt
base-java/package_dedupe/package_dedupe.go
base-java/pom.xml
base-java/requirements.txt
base-java/setup.py
base-java/test/test_base_java_image.py
base-java/tox.ini
base-java/ub/go.mod
base-java/ub/go.sum
base-java/ub/testResources/sampleLog4j.template
base-java/ub/ub.go
base-java/ub/ub_test.go
pom.xml

a new image cp-base-java has been added. The base image consists of ubi9-minimal and jre
This image will be used to refresh component docker images
https://semaphore.ci.confluent.io/workflows/d2b7afc3-59e7-41e1-9437-eccead7388fb/summary?pipeline_id=74caf568-c5c8-466f-a4fc-ba0c4ece0f5c

add new base image based on ubi9-minimal

---

service.yml

add cp-base-java for build deploy

---

pom.xml

This PR updates  glibc and curl version for 7.9.0-rc250206055711 branch to the newly available versions.
PR checks.

Update glibc and curl version for 7.9.0-rc250206055711 branch

---

pom.xml

(cherry picked from commit e4c13a10fa24c5fe5d81a1b63459a6c35cb9454a)
This PR updates glibc and curl version for 7.9.0 versioned branch to the newly available versions.
PR checks.

Update glibc and curl version for 7.9.0 versioned branch

---

pom.xml

This PR will fix the conflicts for master since master has ubi9 image as well

Fix master conflicts for update base os

---

pom.xml

Getting below error
```
[INFO] Error: Unable to find a match: glibc-2.28-251.el8_10.11 glibc-common-2.28-251.el8_10.11 glibc-minimal-langpack-2.28-251.el8_10.11
```
Bumping up glibc package version to resolve the same
PR check

CPBR-2295 Bump up glibc package version

---

base/requirements.txt
pom.xml

This PR will fix merge conflict for updating confluent-docker-utils

Merge conflict resolution 7.3.x to 7.4.x

---

base-java/Dockerfile.ubi8

CPBR-2301 change ownership of directories and add license file

---

.semaphore/cp_dockerfile_build.yml

we need to skip tests in maven deploy stage as well
Continuation to #663

CPBR-2301 skip tests in maven deploy stage

---

pom.xml

This PR upgrades the glibc version to the latest available version for 7.9.0-post branch for ironbank release.
PR checks.

CPBR-2311: Upgrade glibc version for 7.9.0-post branch for ironbank release

---

pom.xml

CPBR-2079 update base os

---

.semaphore/semaphore.yml
utility-belt/pom.xml
utility-belt/src/test/java/io/confluent/admin/utils/ClusterStatusSASLTest.java
utility-belt/src/test/java/io/confluent/admin/utils/ClusterStatusTest.java
utility-belt/src/test/java/io/confluent/admin/utils/ClusterWaitTest.java
utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java
utility-belt/src/test/java/io/confluent/admin/utils/TopicEnsureTest.java

1. Use KafkaClusterTestKit instead of deprecated TestUtils methods
2. Remove zookeeper wait/healthchecks
3. Modify EmbeddedKafkaCluster to work without zookeeper param

CPBR-2233 Remove zk usage and add kraft tests

---

base/pom.xml
pom.xml

This PR is needed to reduce merge conflicts once we migrate to ubi9 as part of #668

CPBR-2316 rename properties to ubi8

---

base/pom.xml

fix build args for 7.7.x due to args not updated through pint merge

fix build args for crypto policies and findutils

---

base/pom.xml

fix version for findutils

---

pom.xml

This PR will update base os of the 7.7.0-cp9 branch

Update base os for 7.7.0-cp9 branch

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml
service.yml

- built on top of https://github.com/confluentinc/common-docker/pull/699
- 7.4.x has additional docker image, so had to re-apply svc bot changes

cpbr-2445 apply service bot changes

---

pom.xml

CPBR-2278 upgrade golang image

---

base/requirements.txt
pom.xml

CPBR-2393 upgrade docker-utils

---

base/requirements.txt
pom.xml

Updating base os and dependencies

CPBR-2493 | Update common-docker dependency for 7.9.1

---

base/requirements.txt
pom.xml

Updating base os for fedRAMP may release

Update base os for Fedramp release

---

pom.xml

Updating the jdk and ubi8 minimal base image versions .
JDK version also updated to latest.

Update jdk and ubi8 minimal base os image versions 7.7.x

---

base/requirements.txt
pom.xml

This PR will update the dependencies and fix CVE for June FEDRAMP release

CPBR-2641 | Update dependency for June FedRAMP release and fix CVE

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml
pom.xml

This PR will update the dependency version of setuptool

Updating setuptools in FedRAMP RC branch

---

pom.xml

update krb5 version

---

pom.xml

fix krb5 version

---

pom.xml

This PR will the INC-3021 which is coming up due to new version is available

INC-3021 | Update glibc version 

---

pom.xml

INC-3067 update glibc version for ubi9

---

pom.xml

Fix dependency for ib release

---

pom.xml

Updating setuptools to fix CVE-2025-47273

CPBR-2661 | Update setuptools to fix the CVE

---

base/requirements.txt
pom.xml

Fix merge conflict for 7.9.x

---

base-java/requirements.txt
base-java/ub/ub.go
base-java/ub/ub_test.go
pom.xml

Update ubi9 minimal and fix merge conflict

---

base/pom.xml
pom.xml

Fix Merge conflict in 7.7.x

---

pom.xml

Merge conflict resolution from 7.6.x to 7.7.x

---

pom.xml

Update Python 3.9 version for ubi9 base

Update Python 3.9 version

---

pom.xml

This will fix the failure related to tar and python dependency version not found failure

CPBR-3089 | Updating tar and python version in versioned branch

---

pom.xml

This PR cherry-picks the changes from https://github.com/confluentinc/common-docker/pull/842 into `7.6.7`.

CPBR-3089 | Updating tar and python version in 7.6.7 branch

---

pom.xml

This PR cherry-picks the changes from https://github.com/confluentinc/common-docker/pull/842 into `7.5.10-rc250912100603`.

CPBR-3089 | Updating tar and python version in 7.5.10-rc250912100603 branch

---

pom.xml

This PR cherry-picks the changes from https://github.com/confluentinc/common-docker/pull/842 into `7.3.14-rc250912100603`.

CPBR-3089 | Updating tar and python version in 7.3.14-rc250912100603 branch

---

pom.xml

This PR upgrades to latest ubi 8 minimal version - 8.10-1756195339
PR checks

CPBR-3052: Upgrade to latest ubi 8 minimal version
