confluentinc/common-docker

.gitignore, base/Dockerfile, base/include/etc/confluent/docker/bash-config
They will be used in downstream projects, like ksql, to simplify and
unify the configuration and common functions.
See related https://github.com/confluentinc/cp-docker-images/pull/606
=> CP-578: Add common bash config and functions

Jenkinsfile, base/tox.ini
Eventually we will want to unpin this, but we need to retire py27 generally before we do that.
Also fixes the Jenkinsfile to move away from the deprecated docker_oraclejdk8 name.
=> MINOR: Pin Sphinx<2.0.0 to maintain py27 compatibility

utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java
https://github.com/apache/kafka/commit/8e161580b859b2fcd54c59625e232b99f3bb48d0 changed the signature of `TestUtils.createBrokerConfig`. This change fixes the call here to reflect that change.
=> Fix compilation error due to changed signature of test util

base/tox.ini
pin pytest versions since pytest 5.0.0 do not support python 2.7 anymore. Target from 4.0.x branch.
=> pin pytest versions

base/Dockerfile
/usr/local/bin/dup needs the paramiko that needs build-essential libssl-dev libffi-dev python-dev.
=> Add packages for installing paramiko.

utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedZookeeperEnsemble.java
And whitelist 4lw commands in tests (necessary since ZK 3.5.3).
=> Fix compilation with zookeeper 3.5.5

Jenkinsfile, jmxterm/Dockerfile, jmxterm/pom.xml, kerberos/Dockerfile, kerberos/config.sh, kerberos/pom.xml, pom.xml
Several of the docker image tests depend on these jmxterm and kerberos docker images. I am trying to revive these tests and get them running again so we need to start building these test images again. Since they are shared among several repos I am adding them to the common-docker repo.
=> Adding jmxterm and kerberos images required for testing

base/Dockerfile, base/include/etc/confluent/docker/mesos-setup.sh
The old cp-docker-image have that file in base image, some images is using it, we should add it back.
Also there is krb client setup on old base image, we might want to it back either.
=> add mesos-setup.sh back

base/Dockerfile
The rhel base image is missing ping. This will install iputils to the base image which includes ping.
=> ST-2548: Adding iputils which includes ping to the base image

base/requirements.txt
When building the base image we install the confluent-docker-utils module which requires boto which requires python-dateutil. For some reason there is an issue with the python-dateutil module because when it goes to install the latest version 2.8.1 something gets messed up and it reports that it is installing version None, and then when running dub which depends on that module it fails saying the module can not be found. If we explicitly try and install version 2.8.1 we get the same issue, so there must be an issue with that package on our pypi server or something to that affect. If we explicitly install python-dateutil 2.8.0 prior to installing confluent-docker-utils then it installs correctly and everything works.
=> ST-2560: Explicitly set python-dateutil to version 2.8.0

docker-utils/pom.xml
Currently images are failing as they are not able to access zk-ready and kafka-ready.  These are part of utility belt and the base image only includes docker-utils.  Adding the dependency.
=> update pom for docker-utils to include utility-belt dependency

Jenkinsfile
We should be using the new docker swarm nodes because the pool is much bigger.
=> Use docker swarm nodes

Jenkinsfile
I am disabling the cron schedule because it will always fail because these builds require parameters to be passed in.
=> Disable cron schedule

Jenkinsfile
The common-docker repo now depends on the packaging build, so anytime the upstream dependencies that were listed in here triggered this build it would fail because they don't and can't provide the necessary build parameters. So I am removing these upstream dependencies so we stop getting a bunch of failed builds.
=> Remove upstream job dependencies

base-deb8/Dockerfile
The debian packaging repository gets added in each of the docker image so we don't need to add it in the base image as well. This is throwing warnings in our builds that the repository was added twice.
=> ST-2731: Do not add packaging debian repository to old base image

base/Dockerfile.deb8, base/Dockerfile.deb9, base/Dockerfile.rhel8
Previously added python modules that are required by dub were built from source. In order to build them from source it required additional packages to be installed. Those additional packages made a significant increase in the size of the base images. By installing the python modules from a binary distribution we don't need those additional packages installed so the image size does not increase nearly as much. The Jira ticket has a lot more details on this.
I tested this by building all three docker images locally and then running the ksql-images build to verify it still works. The ksql-images build was previously failing when these new python modules were not installed. I also verified the size of the new docker images. There is still a small increase in the image size vs. the 5.3.x …
=> ST-2791: Install python modules from binary packages and remove packages installed only for building python modules

utility-belt/src/test/java/io/confluent/admin/utils/ClusterWaitTest.java, utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java
https://confluentinc.atlassian.net/browse/ST-2854
We have seen common-docker build test failures due to port conflicts. This PR updates the test to use random port while running tests.
=> ST-2854: Use random ports while running Kafka server in tests

base/Dockerfile.ubi8, base/license.txt
In order to pass the redhat container registry scan we need to have a licenses folder with a license in it. Since we haven't decided on the license we want to use I am creating the folder and copying the apache license that we already have in this repo. I think we will end up using this license in the end because the license is only for the image build and not the other software we install. Since the CP packages we install already have licenses those will apply for those products, and this just applies to the docker file.
=> ST-2560: Adding licenses to rhel image

base/README.md
I am updating the readme to include a description of the two arguments required to build the images using the packages from the s3 repo.
=> ST-2560: Adding instructions for building with packages to the readme file.

base/Dockerfile.ubi8
This will set the default python version to python3. So when you just run python now it will work and use the installed version of python3. I tested this by building the docker image locally, starting a container from that image and running python to make sure it worked.
=> ST-2952: Setting default python to python3 in ubi8 image

base/Dockerfile.ubi8
We need to create the /usr/logs folder in the ubi8 image because some of our apps want to write to that folder and they can not create it because /usr is owned by root and we are now running as appuser. This will create the /usr/logs folder and assign ownership of it to the appuser
=> ST-2963: Creating /usr/logs/ folder as appuser in ubi8 image

base/Dockerfile.ubi8
For the 6.0.0 release we are going to run JDK11 in our docker images. This upgrades the ubi8 base image to JDK11, but not the debian images because we are supposed to deprecate them in the 6.0.0 release.
=> ST-2950: Upgrading jdk to zulu-11-11.37+17-1 in the ubi8 base image

base/Dockerfile.ubi8
Downgrading to version 11.0.5 because the 11.0.6 version introduced a change that causes an issue with our products. Details about the issue are in the ticket ST-2950 and https://confluentinc.atlassian.net/browse/ESCALATION-2286
=> ST-2950: Downgrading ubi8 to jdk 11.0.5+10 because of issue withe 11.0.6

base/Dockerfile.ubi8
This will make so we install python 3.6.8 so that we can reproduce the base image with that exact version instead of always getting the latest python 3 version.
=> ST-3165: Using explicit python3 version in ubi image

base/pom.xml
This will enable the new parameter to always pull down the OS base image instead of using a local version.
=> ST-3255: Set parameter to always pull latest version of the os base image when building cp-base-new

base/requirements.txt
Bump confluent-docker-utils to have the fix https://github.com/confluentinc/confluent-docker-utils/pull/16
Not sure if we should apply the same fix for cp-docker-images? https://github.com/confluentinc/cp-docker-images/blob/5.3.1-post/debian/base/Dockerfile#L83 Seems they share different versions.
=> bump confluent-docker-utils

base/Dockerfile.ubi8
We need to install the hostname utility on the ubi8 docker images because other images require it, such as zookeeper when it starts up.
=> ST-3334: Install hostname app in ubi8 base image

base/Dockerfile.ubi8
Problem:
Yum installation requires older packages that were upgraded in the new image version: ubi-minimal:8.1-409
Original PR: https://github.com/confluentinc/common-docker/pull/70
Ticket:  https://confluentinc.atlassian.net/browse/ST-3476
Solution:
Temporary revert to older images until issue is fixed by Redhat.
=> Revert ubi-minimal version

base/Dockerfile.ubi8
RedHat fixed the bug with the latest image that was causing us an issue so I am setting our base image back to using the latest available version.
=> ST-3550: Use latest vesion of ubi8-minimal image

base/requirements.txt
Bump confluent-docker-utils to 0.0.38 to install module `six`. Ksql-images(after 5.4.x) are currently failing on 
```
ImportError: No module named six
```
related pr: https://github.com/confluentinc/confluent-docker-utils/pull/22
=> Bump confluent-docker-utils to 0.0.38

base/Dockerfile
In the new zulu open jdk image, they switch debian base version to debian 10 buster, which broken the python thing, I am not sure whether it can break more things. So I pin the version to be `8u242` which is release 3 months ago and still use debian 9 stretch.
=> pin zulu image version

base/Dockerfile.deb8
Akin to https://github.com/confluentinc/cp-docker-images/pull/853 but need to make the similar change here.
=> Stop installing deprecated source lists

base/include/etc/confluent/docker/bash-config
We don't want to print the environment variables in the logs during startup because they contain sensitive data.
=> ST-3599: Remove show_env function because it exposes secrets

jmxterm/Dockerfile.deb8, jmxterm/Dockerfile.deb9, jmxterm/Dockerfile.ubi8, pom.xml
I am enabling the build for the jmxterm image for deb8, deb9, and ubi8.
=> ST-3779: Enable build for jmxterm image

jmxterm/Dockerfile.deb8, jmxterm/Dockerfile.deb9, jmxterm/Dockerfile.ubi8
Upgrading the version of jmxterm in the jmxterm image to a stable newer release version (1.0.1) from an older version. Built and ran the Docker image using the newer version successfully to test it. Started jmxterm in the container and verified that it was using the newer version using the "about" command.
=> ST-3784: Upgraded the version of jmxterm to 1.0.1 in the jmxterm image

Jenkinsfile
When I re-enabled the build for cp-jmxterm images I forgot to update the jenkins file which requires a list of the docker images being built. Since this image wasn't in the list it was building the images but not tagging them and uploading them to ECR. This will make sure they are tagged and uploaded.
=> ST-3784: Fix jenkins file to tag and push cp-jmxterm images

pom.xml
Since we no longer build debian images the default image os type should be ubi8. It looks like I missed this when removing the debian images.
=> Set default image type to ubi8

base/Dockerfile, base/requirements.txt
`--install-option` causes `pip` to not use any wheel files, which causes issues for `pynacl` that will attempt compilation (and requires  `libssl-dev`). It is better to use `--prefix` option instead.
=> ST-3962: update confluent-docker-utils to latest

base/Dockerfile.ubi8
It was discovered that `cp-server` and `cp-server-connect` images are all running different Java versions, to summarize this is the reason why:
* cp-base-new - installs an (outdated) azul yum repo - We are pinning that version to zulu-11-11.35+15-1 in the base - which equates to Java “11.0.5” https://github.com/confluentinc/common-docker/blob/6.0.x/base/Dockerfile.ubi8#L57-L58
* cp-server Inherits from cp-base-new, runs an unbounded yum update and updates to zulu-11-11.39+15-2 (which roughly equates to Java “11.0.7") , which also pulls in a zulu-repo that installs a different/seemly more-updated yum repo https://github.com/confluentinc/kafka-images/blob/6.0.x/server-connect-base/Dockerfile.ubi8#L50
* cp-server-connect-base inherits from cp-server, and now that cp-server installed a …
=> Use a more up-to-date Azul repo

base/Dockerfile.deb8, base/Dockerfile.deb9, base/Dockerfile.ubi8
"backporting" https://github.com/confluentinc/common-docker/pull/100
* Use more up to date Zulu Repo
* Install latest zulu-8 JVM (as of today) (in both debs & ubi images)
=> ST-4157: Use more up-to-date zulu repo

base/Dockerfile
Bumping this base image for ksql's-derrived image in 5.3.x world.
=> Bump cp-base-new 53x to 8u262

base/Dockerfile, base/test/test_base_image.py
The update here https://github.com/confluentinc/common-docker/pull/101 changed the Debian base image from deb9 to deb10, thats a nono in our book.
I'm also adding a test from https://github.com/confluentinc/common-docker/pull/103 to pick up regressions.
=> Undo update to azul/zulu-openjdk-debian:8u262 & add test

base/requirements.txt
The 5.4.x -> master jobs are failing to build UBI8 Images because the location of the dub/cub python scripts moved from (expected) `/usr/local/bin` to (now) `/usr/bin`.
It seems there was a setuptools release over the weekend:
```
-  Downloading https://files.pythonhosted.org/packages/c3/a9/5dc32465951cf4812e9e93b4ad2d314893c2fa6d5f66ce5c057af6e76d85/setuptools-49.6.0-py3-none-any.whl (803kB)
+  Downloading https://files.pythonhosted.org/packages/b0/8b/379494d7dbd3854aa7b85b216cb0af54edcb7fce7d086ba3e35522a713cf/setuptools-50.0.0-py3-none-any.whl (783kB)
```
This release has seemed to have caused a lot of issues in the community: https://github.com/pypa/setuptools/issues/2352
Their solution is to pin bellow 50.0.0 until its fixed, which is what we're doing here.
=> Pin setuptools<50.0.0

base/requirements.txt
Followup to https://github.com/confluentinc/confluent-docker-utils/pull/24
=> Bump confluent-docker-utils to v0.0.40

utility-belt/pom.xml
We're getting a build issue here:
```
16:27:38  [INFO] Running io.confluent.admin.utils.ClusterWaitTest
[2020-09-24T23:28:10.187Z] [ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 26.754 s <<< FAILURE! - in io.confluent.admin.utils.ClusterWaitTest
[2020-09-24T23:28:10.187Z] [ERROR] io.confluent.admin.utils.ClusterWaitTest.isKafkaReadyWait  Time elapsed: 0 s  <<< ERROR!
16:28:10  java.lang.NoClassDefFoundError: org/junit/jupiter/api/Assertions
16:28:10  	at io.confluent.admin.utils.ClusterWaitTest.isKafkaReadyWait(ClusterWaitTest.java:85)
16:28:10  Caused by: java.lang.ClassNotFoundException: org.junit.jupiter.api.Assertions
16:28:10  	at io.confluent.admin.utils.ClusterWaitTest.isKafkaReadyWait(ClusterWaitTest.java:85)
```
@ewencp believes it may be due to this …
=> Specify org.junit.jupiter:junit-jupiter-api:5.7.0 as test dependency

utility-belt/pom.xml
Follow-up to https://github.com/confluentinc/common-docker/pull/111 but this time, using the property I defined in the common project: https://github.com/confluentinc/common/pull/299
=> MINOR: Use junit.jupiter.version property

Jenkinsfile, base/pom.xml, docker-utils/pom.xml, jmxterm/pom.xml, kerberos/pom.xml, pom.xml, utility-belt/pom.xml
Setting the jenkins config to use nano versioning. Removed all of the snapshot versions and replaced with nano versions. Updated all of the dependency versions.
These changes will be merged during phase two of the nano versioning roll out.
=> ST-3461: Implement nano versioning

base/requirements.txt
Helper PR to test https://github.com/confluentinc/confluent-docker-utils/pull/28
~~Provided that this builds & tests fine, then I will merge the above PR, and then change `ST-4684` to the tagged release.~~ Merged, so now this PR is for pinning that tag-ed version of `v0.0.42`
The removals of:
```
python-dateutil==2.8.0
setuptools<50.0.0
```
Were there for python27-compat reasons, in 6.0.x going forward, we only care about python3, and therefore justified IMO. I have branched `python27-compat` from `v0.40.0` where we'll maintain python27-compatible dependency sets for the older docker images (5.0.x -> 5.5.x)
=> Use 0.0.42 release of confluent-docker-utils

base/Dockerfile.deb8
Similar to https://github.com/confluentinc/cp-docker-images/pull/894 but for the newer docker images.
=> fix: Pin bootstrap.pypa to Python2.7 script

base/Dockerfile.ubi8
- cryptography requires newer setuptools/pip in order to build
- Invoke pip through 'python3 -m pip ...' as per https://github.com/pypa/pip/issues/5599
Our builds are failing at:
```
10:29:00  [INFO] Collecting cryptography>=2.6.1 (from confluent-docker-utils==0.0.42->-r requirements.txt (line 1))
10:29:01  [INFO]   Downloading https://files.pythonhosted.org/packages/35/52/a3b9c3d8ce84544bfe8d663ba993e0593d9c518d6c08f01f6f8fff87b895/cryptography-3.4.2.tar.gz (544kB)
10:29:01  [INFO]     Complete output from command python setup.py egg_info:
10:29:01  [INFO]     
10:29:01  [INFO]             =============================DEBUG ASSISTANCE==========================
10:29:01  [INFO]             If you are seeing an error here please try the following to
10:29:01  [INFO] …
```
=> Upgrade Pip & Setuptools to install newer cryptography library

base/Dockerfile.ubi8
- Use docker-utils v0.0.42 for Py3.x compat modules
- cryptography requires newer setuptools/pip in order to build
- Invoke pip through 'python3 -m pip ...' as per https://github.com/pypa/pip/issues/5599
Backport of https://github.com/confluentinc/common-docker/commit/bf6da34a521f720ae22d166f8aae4c7c61becb7b of sorts. We are also having the UBI image use a newer version of docker-utils to obtain updated python modules that fix CVEs:
* https://confluentinc.atlassian.net/browse/ST-4977
* https://confluentinc.atlassian.net/browse/ST-4979
* https://confluentinc.atlassian.net/browse/ST-4978
PR build shows:
```
[2021-02-09T19:40:03.753Z] [INFO] Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 PyYAML-5.4.1 attrs-20.3.0 bcrypt-3.2.0 boto3-1.9.128 botocore-1.12.253 cached-property-1.5.2 …
```
=> Upgrade Pip & Setuptools to install newer cryptography library (#119)

utility-belt/pom.xml
Builds here are failing after https://github.com/apache/kafka/commit/7a3ebbebbc6aed2049f22c650a52f6f685546207 was merged in, which killed this projects transitive dependency on zookeeper, so we declare it directly now.
=> Build: Move zookeeper to direct compile scope

utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java
Upstream change that triggered this: https://github.com/confluentinc/kafka/commit/e8754ba7a01f33ba503ef79de66a5f644cc2ced8
```
[2021-04-06T16:36:06.950Z] [ERROR] COMPILATION ERROR : 
09:36:06  [INFO] -------------------------------------------------------------
[2021-04-06T16:36:06.951Z] [ERROR] /home/jenkins/workspace/onfluentinc_common-docker_master/utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java:[138,37] cannot find symbol
09:36:06    symbol:   variable SASL_ENABLED_MECHANISMS
09:36:06    location: class org.apache.kafka.common.config.SaslConfigs
```
=> fix: Use BrokerSecurityConfigs after SaslConfigs deprecation

base/Dockerfile.ubi8, base/README.md, base/pom.xml, pom.xml
This does a few things:
* Pins versions of packages we install from Redhat for reproducible builds
* Add check in Dockerfile to fail the build if the package manager detects any available security updates are available.
* Add an "escape hatch" for the above feature in the event you want to build a container thats not going to pass security scans.
I managed to test point 2 by removing the `--security` (because there were non-security updates) switch and built - Indeed the build fails, but would pass if I specified `-Ddocker.dont.fail.if.security.update.availible=true` on the maven CLI.
=> build: Pin UBI package versions. Add security check update

base/Dockerfile.ubi8, base/pom.xml
This commit adds jolokia & prometheus java agents as
dependency to CP base and adds relevant jars to the
docker image.
Relevant updates to `common` (dependency): https://github.com/confluentinc/common/pull/322 (This change will need to be merged/built/deployed before we can get a passing PR build here)
(https://confluentinc.atlassian.net/browse/ST-4106)
=> ST-4106: Uplift metrics related jars to CP Images

utility-belt/src/main/java/io/confluent/admin/utils/cli/TopicEnsureCommand.java
- This Fix only last topic spec mismatch failure in cub script, this will return an error if any topic does not match from actual topic spec
- There is a bug in the cub script that returns only the error status of the last checked topic.
[LOGGING-308](https://confluentinc.atlassian.net/browse/LOGGING-308)
- https://github.com/confluentinc/confluent-docker-utils/blob/master/confluent/docker_utils/cub.py#L348
=> Fix: only last topic spec mismatch failure in cub script

utility-belt/pom.xml
excluding netty code from zk dependency and adding dependency on newer version of netty codec to address CVE
=> ST-5293: Depending on explicit version of netty codec to address CVE

utility-belt/pom.xml
This netty version property is now defined in common so no need to have it defined here as well.
=> ST-5293: Cleanup of netty version property

pom.xml
- Ubi base image version
- Versions of packaegs: procps, krb5-workstation & iputils
Docker Build for this image is failing:
```
02:53:56  [INFO] No match for argument: procps-ng-3.3.15-3.el8_3.1
02:53:56  [INFO] No match for argument: krb5-workstation-1.18.2-5.el8
02:53:56  [INFO] No match for argument: iputils-20180629-2.el8
02:53:56  [INFO] Error: Unable to find a match: procps-ng-3.3.15-3.el8_3.1 krb5-workstation-1.18.2-5.el8 iputils-20180629-2.el8
```
So I loaded up the container, saw there was a base image update to 8.4-200, checked the latest versions available, and updated the defined versions accordingly. 
Its not clear to me why Redhat stripped released software from their repos, when we were pinning to the 8.3 release, so 🤷 - I'll open a support case with them to see what they …
=> build: Update pinned dependencies

base/Dockerfile.ubi8
Redhat doesn't seem to be publishing erratas for their UBI image repos, so the `--security` flag isn't really doing anything in terms of the original intent - which is to fail the build if an update is found, but not installed. Case in point, the `glib2` update that propted this update https://github.com/confluentinc/common-docker/pull/138 didn't fail the build. Yet if we didn't have the `--security` flag, it would have worked. This change removes the flag so now the job will just fail if theres *any* update.
=> build: Remove security flag from yum update check to fail on any package update

pom.xml
New container revision 205 is out: https://catalog.redhat.com/software/containers/ubi8-minimal/5c64772edd19c77a158ea216?tag=8.4-205&push_date=1624986558000&container-tabs=overview
Build is blocked on consuming those updates:
```
11:42:15  [INFO] Step 35/42 : RUN yum --disablerepo=zulu check-update || "${SKIP_SECURITY_UPDATE_CHECK}"
11:42:15  [INFO] 
11:42:15  [INFO]  ---> Running in b96cd8d34a94
11:42:15  [INFO] No repository match: zulu
11:42:15  [INFO] 
11:42:15  [INFO] Red Hat Universal Base Image 8 (RPMs) - BaseOS  7.4 MB/s | 786 kB     00:00    
11:42:16  [INFO] Red Hat Universal Base Image 8 (RPMs) - AppStre  18 MB/s | 2.4 MB     00:00    
11:42:16  [INFO] Red Hat Universal Base Image 8 (RPMs) - CodeRea 191 kB/s |  15 kB     00:00    
11:42:16  [INFO] zulu-openjdk - Azul Systems …
```
=> sec: Update UBI base image to 8.4-205

base/Dockerfile
Confluent Docker Utils version 0.0.42-python2 strips some needless runtime dependencies.
=> build: Install v0.0.42-python2

base/Dockerfile.ubi8, pom.xml
We want to consume a security update: https://www.oracle.com/security-alerts/cpujul2021.html
```
docker run -it placeholder/confluentinc/cp-base-new:5.4.5-SNAPSHOT-ubi8 java -version
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Zulu 8.56.0.21-CA-linux64) (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Zulu 8.56.0.21-CA-linux64) (build 25.302-b08, mixed mode)
```
=> MINOR: Pin Zulu OpenJDK JRE Headless to 8.0.302

utility-belt/src/main/java/io/confluent/admin/utils/ZookeeperConnectionWatcher.java, utility-belt/src/main/java/io/confluent/admin/utils/cli/ZookeeperReadyCommand.java
PR https://github.com/confluentinc/common/pull/364 updated version of checkstyle, causing the build to fail on these linits:
```
15:53:09  [ERROR] /home/jenkins/workspace/onfluentinc_common-docker_master/utility-belt/src/main/java/io/confluent/admin/utils/ZookeeperConnectionWatcher.java:3: <p> tag should be placed immediately before the first word, with no space after. [JavadocParagraph]
15:53:09  [ERROR] /home/jenkins/workspace/onfluentinc_common-docker_master/utility-belt/src/main/java/io/confluent/admin/utils/ZookeeperConnectionWatcher.java:3: <p> tag should be preceded with an empty line. [JavadocParagraph]
15:53:09  [ERROR] /home/jenkins/workspace/onfluentinc_common-docker_master/utility-belt/src/main/java/io/confluent/admin/utils/ZookeeperConnectionWatcher.java:7: <p> tag should be …
```
=> doc: Fix checkstyle errors from checkstyle update

utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedZookeeperEnsemble.java
This PR https://github.com/confluentinc/common/pull/371 's update of zookeeper has changed its `QuorumPeer` interface:
```
09:50:08  [INFO] -------------------------------------------------------------
09:50:08  [ERROR] COMPILATION ERROR : 
09:50:08  [INFO] -------------------------------------------------------------
09:50:08  [ERROR] /home/jenkins/workspace/onfluentinc_common-docker_master/utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedZookeeperEnsemble.java:[95,22] no suitable constructor found for QuorumPeer(java.util.HashMap,java.io.File,java.io.File,int,int,int,int,int,int)
09:50:08      constructor org.apache.zookeeper.server.quorum.QuorumPeer.QuorumPeer() is not applicable
09:50:08        (actual and formal argument lists differ in length)
09:50:08      constructor …
```
=> build: QuorumPeer Changes for Zookeeper 3.6

base/Dockerfile.deb8, base/Dockerfile.deb9, base/Dockerfile.ubi8, jmxterm/Dockerfile.deb8, jmxterm/Dockerfile.deb9, jmxterm/Dockerfile.ubi8, kerberos/Dockerfile
Add unique description LABELs to the common-docker images. This was one of the findings from Redhat
This is a superficial change no testing is required.
=> doc: Add description label for all images

pom.xml
What:
Currently only krb5-workstation-1.18.2-8.3.el8_4 is available for ubi image https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/baseos/os/Packages/k/
Zulu repo is missing from current image
How:
Update base image
Update krb5-workstation
Test:
PR build successful.
=> fix: fix krb5-workstation version

base/Dockerfile.ubi8
Drop the Confluent Clients repo in the base image, rather than doing this same thing in downstream Images.
=> feat: Install Confluent yum Repo in cp-base-new

base/Dockerfile.deb8
This contains an expired cert thats blocking the ability to import GPG keys:
```
root@4c33dd1858d0:/# openssl x509 -in /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt -noout -text
Certificate:
Data:
Version: 3 (0x2)
Serial Number:
44:af:b0:80:d6:a3:27:ba:89:30:39:86:2e:f8:40:6b
Signature Algorithm: sha1WithRSAEncryption
Issuer: O=Digital Signature Trust Co., CN=DST Root CA X3
Validity
Not Before: Sep 30 21:12:19 2000 GMT
Not After : Sep 30 14:01:15 2021 GMT
```
Similar fix vended here: https://github.com/confluentinc/cp-docker-images/pull/907
=> build: Remove expired ca-cert

base/Dockerfile.ubi8
This is a walk back of https://github.com/confluentinc/common-docker/pull/154 - Downstream CP images will need to add the confluent repo themselves, then remove it.
=> build: Remove confluent yum repo.

pom.xml
Builds today were flagging that there are un-upgraded dependencies. Checking Redhat's UBI Image website
https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?container-tabs=packages
Indeed, there is a new base image revision `8.4-212` that is available.
=> build: Update UBI Base Image to 8.4-212

base/Dockerfile.ubi8
This change makes it so any invocations of `yum` or `dnf` will skip installing any %doc tagged files from the base OS image (and Java vendor). This creates a smaller image overall as well as reduces false positives on security scans.
wrt to security scans for example, the `krb5-workstation` package is shipping a vulnerable `/usr/share/doc/krb5-workstation/_static/jquery-3.2.1.js` file, which isn't in code paths for CP, but is being picked up by security scanners. So instead of fighting this for every false positive that gets raised, we just disable installing all %doc files in the first place.
=> feat: Add yum --nodocs to disable installing %doc files.

pom.xml
New release of openssl:
```
[root@c9689a661b56 /]# rpm -q --changelog openssl | head
* Fri Nov 12 2021 Sahana Prasad <sahana@redhat.com> - 1:1.1.1k-5
- CVE-2021-3712 openssl: Read buffer overruns processing ASN.1 strings
- Resolves: rhbz#2005400
```
=> chore: Update openssl to 1.1.1k-5.el8

utility-belt/pom.xml, utility-belt/src/main/java/io/confluent/admin/utils/cli/KafkaReadyCommand.java, utility-belt/src/main/java/io/confluent/admin/utils/cli/TopicEnsureCommand.java, utility-belt/src/main/java/io/confluent/admin/utils/cli/ZookeeperReadyCommand.java
Abandoned approach here: https://github.com/confluentinc/common-docker/pull/169
Ever so slightly better approach from https://github.com/confluentinc/common-docker/commit/3b75337ba3292f7364824bdf19ba1dbfd0fe6777 - this time, we're not specifing a `<version>` block, so release-tools won't munge it when RCs are created. 
Testting (from a build on master, as it seems this issue only affects 7.0.0 images):
```
aegelhofer@Andrew-Egelhofer's- common-docker % docker run -it ....dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-base-new:dev-master-2006-ubi8 cub kafka-ready 1 1 -b ....gcp.confluent.cloud:9092
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/java/cp-base-new/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found …
```
=> fix: Initialize log4j in admin.utils Commands

base/requirements.txt
Updated confluent-docker-utils to latest version (v0.0.49).
This is a prerequisite for https://github.com/confluentinc/kafka-images/issues/92.
=> update confluent-docker-utils to v0.0.49

pom.xml
New image revision is out, and while it doesn't contain any security fixes, we may as well update it.
=> build: Update base image to 8.5-230

pom.xml
There is a new Zulu JDK release we are not installing, this PR changes that.
=> chore: Update zulu.openjdk.version to 11.0.14.1

pom.xml
Update image revision to latest ubi-minimal image version, 8.5-240
To be cherry picked into 5.4.0-post after, then pint merged up
=> build: Update base image to 8.5-240

pom.xml
Already cherry-picked into Q1 patch releases to get them building and out the door, now properly backporting into all branches
To be picked into 5.4.0-post and pint merged upwards
=> Update base image to 8.5-240.1648458092

pom.xml
```
11:26:17  [INFO] zulu-openjdk - Azul Systems Inc., Zulu packages 3.0 MB/s | 348 kB     00:00    
11:26:17  [INFO] No match for argument: iputils-20180629-7.el8
11:26:17  [INFO] [91mError: Unable to find a match: iputils-20180629-7.el8
```
Following troubleshooting instructions in https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/2565472764/Troubleshooting#The-command-'/bin/sh--c-yum-check-update-||-%22${SKIP_SECURITY_UPDATE_CHECK}%22'-returned-a-non-zero-code:-1in-common-docker
Loaded up base image with `docker run -it redhat/ubi8-minimal:8.5-243.1651231653`, ran `yum list --showduplicates iputils`, and it showed that there's an update to iputils and latest version should be `20180629-9.el8`
To be pint merged into `-post` and `.x` branches
**EDIT:**  Initial PR build failed …
=> [chore] Update iputils to 20180629-9.el8

base/pom.xml, utility-belt/pom.xml
Description
This is a request to migrate from confluent-log4j to reload4j
Jira Ticket:
DP-7573
Resolution
Step 1: Replace slf4j-log4j12 with slf4j-reload4j.jar
Step 2: Remove Confluent-log4j
Step 3: Add dependency on Logredactor
=> Migrate log4j to reload4j

.github/CODEOWNERS
This repo is owned by tools, removing @/team to reduce noise
To be pint merged up to master
=> Remove team from codeowners

base/requirements.txt, pom.xml
Bump confluent-docker-utils to v0.0.52
To be pint merged up through master
=> [chore] Bump confluent-docker-utils to v0.0.52

pom.xml
common-docker builds failing: 
https://confluentinc.atlassian.net/browse/DP-8093
https://confluentinc.atlassian.net/browse/DP-8094
https://confluentinc.atlassian.net/browse/DP-8096
Error:
`[ERROR] The command '/bin/sh -c yum check-update || "${SKIP_SECURITY_UPDATE_CHECK}"' returned a non-zero code: 1`
Resolution: 
Update redhat ubi base image
https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/2565472764/Troubleshooting#The-command-'/bin/sh--c-yum-check-update-||-%22${SKIP_SECURITY_UPDATE_CHECK}%22'-returned-a-non-zero-code:-1in-common-docker
5.4.x pint merge to master; skipping 5.3.x (uses `azul/zulu-openjdk-debian:8u242`) since it does not use redhat ubi image
=> chore: update base image

pom.xml
Build error:
```
zulu8-ca-jdk-headless.x86_64               8.0.342-1                zulu-openjdk
03:35:10  [INFO] zulu8-ca-jre-headless.x86_64               8.0.342-1                zulu-openjdk
03:35:10  [ERROR] The command '/bin/sh -c yum check-update || "${SKIP_SECURITY_UPDATE_CHECK}"' returned a non-zero code: 1
```
Following troubleshooting steps https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/2565472764/Troubleshooting#The-command-'/bin/sh--c-yum-check-update-%7C%7C-%22$%7BSKIP_SECURITY_UPDATE_CHECK%7D%22'-returned-a-non-zero-code:-1in-common-docker
There is an available base image version update 8.6-902, as well as updates to latest openssl and openjdk versions available on it.
To be pint merged up (6.0.x+ will be using zulu11 `11.0.16-1`)
=> [chore] Update base image, openssl, and openjdk

docker-utils/main/resources/log4j.properties, utility-belt/src/main/java/io/confluent/admin/utils/cli/KafkaReadyCommand.java, utility-belt/src/main/java/io/confluent/admin/utils/cli/TopicEnsureCommand.java, utility-belt/src/main/java/io/confluent/admin/utils/cli/ZookeeperReadyCommand.java
**Context:**
For https://confluentinc.atlassian.net/browse/DP-8414
Right now, the shown logging level in [confluent-docker-utils/cub.py at master](https://github.com/confluentinc/confluent-docker-utils/blob/master/confluent/docker_utils/cub.py#L160-L172) is DEBUG. Investigation by appsec team showed that the 1.7.36 version of slf4j caused the logging level to default to DEBUG, potentially showing more information than is desired when cub is ran. cub is just a wrapper around calling Java with the `io.confluent.admin.utils.cli.KafkaReadyCommand` class, so we need to fix `KafkaReadyCommand` class here to not show DEBUG logs.
[This solution](https://stackoverflow.com/questions/2453010/log4j-rootlogger-seems-to-inherit-log-level-of-other-logger-why) suggests that we disable additivity to …
=> Configure loggers from log4j properties

base/pom.xml, docker-utils/pom.xml
Context:
Starting in 7.2.x, common-docker brings in both `slf4j-simple` and `reload4j`, both of which are built on `slf4j-api`. As a result, we get a warning about multiple slf4j bindings when running our docker images. Further details at http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Changes:
This removes use of slf4j-simple in 7.2.x and up (where reload4j already exists) to avoid showing multiple binding warning in our images.
=> Remove slf4j-simple to avoid double binding with reload4j

base/Dockerfile.ubi8, base/pom.xml, pom.xml
5.4.x and newer versions are failing due to:
```
03:40:43  [INFO] Step 38/45 : RUN yum check-update || "${SKIP_SECURITY_UPDATE_CHECK}"
03:40:43  [INFO] 
03:40:43  [INFO]  ---> Running in 6a6db3c2e676
03:40:43  [INFO] Red Hat Universal Base Image 8 (RPMs) - BaseOS  6.9 MB/s | 801 kB     00:00    
03:40:44  [INFO] Red Hat Universal Base Image 8 (RPMs) - AppStre  19 MB/s | 3.0 MB     00:00    
03:40:44  [INFO] Red Hat Universal Base Image 8 (RPMs) - CodeRea 246 kB/s |  20 kB     00:00    
03:40:44  [INFO] zulu-openjdk - Azul Systems Inc., Zulu packages 2.3 MB/s | 418 kB     00:00    
03:40:45  [INFO] 
03:40:45  [INFO] curl.x86_64                     7.61.1-22.el8_6.4                   ubi-8-baseos
03:40:45  [INFO] libcurl.x86_64                  7.61.1-22.el8_6.4 …
```
=> fix: Pin curl and libcurl Versions

docker-utils/main/resources/log4j.properties, utility-belt/src/main/java/io/confluent/admin/utils/cli/KafkaReadyCommand.java, utility-belt/src/main/java/io/confluent/admin/utils/cli/TopicEnsureCommand.java, utility-belt/src/main/java/io/confluent/admin/utils/cli/ZookeeperReadyCommand.java
Revert configuring log4j via `log4j.properties`, as master:latest image is running into issues finding the properties file when attempting to run kafka ready. Unblock it for now until we have a fix.
=> Revert "Configure loggers from log4j properties (#230)"

utility-belt/src/main/java/io/confluent/admin/utils/cli/KafkaReadyCommand.java, utility-belt/src/main/java/io/confluent/admin/utils/cli/TopicEnsureCommand.java, utility-belt/src/main/java/io/confluent/admin/utils/cli/ZookeeperReadyCommand.java, utility-belt/src/main/resources/log4j.properties
- Introduce default config at INFO level for utility command. 
https://confluentinc.atlassian.net/browse/DP-6627?focusedCommentId=736032
=> DP-8414: Add default log4j property 

pom.xml
Steps taken:
1. [cp-docker-images-overlay/6.2.6-cp1](https://jenkins.confluent.io/job/confluentinc/job/cp-docker-images-overlay/job/6.2.6-cp1-rc221011031148/) was failing on common-docker build
2. [common-docker build](https://jenkins.confluent.io/job/confluentinc/job/common-docker/job/6.2.6-cp1-rc221011031148/2/console) was failing on following error
```02:23:36  [INFO] No match for argument: openssl-1.1.1k-6.el8_5
02:23:36  [INFO] Package xz-libs-5.2.4-4.el8_6.x86_64 is already installed.
02:23:36  [INFO] Package glibc-2.28-189.5.el8_6.x86_64 is already installed.
02:23:36  [INFO] Package glibc-common-2.28-189.5.el8_6.x86_64 is already installed.
02:23:36  [INFO] Package glibc-minimal-langpack-2.28-189.5.el8_6.x86_64 is already installed.
02:23:36  [INFO] Error: Unable to find a match: …
```
=> Update openssl version for hotfix

pom.xml
-        <ubi.tar.version>1.30-5.el8</ubi.tar.version>
-        <ubi.procps.version>3.3.15-6.el8</ubi.procps.version>
-        <ubi.krb5.workstation.version>1.18.2-14.el8</ubi.krb5.workstation.version>
-        <ubi.iputils.version>20180629-9.el8</ubi.iputils.version>
+        <ubi.tar.version>1.30-6.el8</ubi.tar.version>
+        <ubi.procps-ng.version>3.3.15-9.el8</ubi.procps-ng.version>
+        <ubi.krb5-workstation.version>1.18.2-21.el8</ubi.krb5-workstation.version>
+        <ubi.iputils.version>20180629-10.el8</ubi.iputils.version>
=> Update package versions for ubi8 8.6-994

utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java
[This recent change](https://github.com/apache/kafka/pull/12783/files#diff-b8f9f9d1b191457cbdb332a3429f0ad65b50fa4cef5af8562abcfd1f177a2cfeR218) to Kafka changed the method signature for a testing utility function, `createBrokerConfig`. From the Scala source code, the default value for this appears to be `false`, but I'm guessing the Scala to Java conversion removed the default value.
=> [chore] Add required argument to createBrokerConfig

.github/CODEOWNERS
I am updating the reference to the "tools" team in the code owners file. Our new GitHub team name is "DevProd".
=> DP-7231: Updating codeowners from tools to devprod team.

base/Dockerfile.deb8, utility-belt/pom.xml
During the Q4 2022 CVE review I have realized that cp-base image keep bringing the outdated snakeyaml dependency. The first suspect jmx_exporter has been mostly addressed, this is the second place where snakeyaml is brought in as a transitive dependency of com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar This will need to be pint-merged to all the branches.
=> Pin Snakeyaml version to resolve multiple CVEs

pom.xml
common-docker builds failing:
https://confluentinc.atlassian.net/browse/DP-10938
Error:
[ERROR] The command '/bin/sh -c yum check-update || "${SKIP_SECURITY_UPDATE_CHECK}"' returned a non-zero code: 1
Resolution:
Update redhat ubi base image
https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/2565472764/Troubleshooting#The-command-'/bin/sh--c-yum-check-update-||-%22${SKIP_SECURITY_UPDATE_CHECK}%22'-returned-a-non-zero-code:-1in-common-docker
=> chore:  update base image

base/Dockerfile.deb9
CP 5.5.x docker image builds were failing for various reasons, some were identified in  DP-10938 but additional problems persisted. 
Debian based images failed to build because apt update command failed due to lack of the package apt-transport-https
package apt-transport-https was installed AFTER apt update succeeds. 
This change allows for installing packages even if apt update fails. 
Changing the order and first installing apt-transport-https before running apt update fails with HTTP errors 404 due to subpatch mismatch 
http://security.debian.org/debian-security/pool/updates/main/n/nghttp2/libnghttp2-14_1.18.1-1+deb9u1_amd64.deb does not exist but, 
http://security.debian.org/debian-security/pool/updates/main/n/nghttp2/libnghttp2-14_1.18.1-1+deb9u2_amd64.deb does...
=> fix catch22 and allow to install deb packages even if apt update fails

base/Dockerfile.ubi8
The ubi8 dockerfile is currently missing the logic to ignore the zulu-openjdk repository when checking for updates. 
The expected behavior as described in the comments is to ignore zulu-openjdk repository as the java version is pinned.
=> add the switch to ignore zulu-openjdk repository when looking for updates

pom.xml
update the zulu openjdk to the latest version. This combined with the flawed logic of checking for updates was causing container builds to fail.
=> update openjdk to the latest version 

base/Dockerfile.ubi8
This PR is all of the changesets that were required to successfully build common-docker for  7.2.1-cp1-rc230206224111, 7.2.2-cp1-rc230109163917 and 7.3.1-cp3-rc230208200712 hotfixes, cherry-picked back into the oldest supported -post branch 5.5.13-post in preparation for pint merge propagation downstream
=> DP-10966 Cherry pick hotfix rc fixes to downstream -post branches

pom.xml
This changes the ubi8-minimal image to the latest version. 
The master build is currently failing like:
```
18:40:39  [ERROR] The command '/bin/sh -c yum --disablerepo="zulu-openjdk" check-update || "${SKIP_SECURITY_UPDATE_CHECK}"' returned a non-zero code: 1
```
https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/2565472764/Troubleshooting#The-command-'/bin/sh--c-yum-check-update-%7C%7C-%22$%7BSKIP_SECURITY_UPDATE_CHECK%7D%22'-returned-a-non-zero-code:-1in-common-docker says this is how to address this.
=> upgrade ubi8-minimal to the latest version

utility-belt/pom.xml
The conflict resolution for first PR for APPSEC-2550 (https://github.com/confluentinc/common-docker/pull/293)  made me realize that we:
- bring outdated version of gson
- bring outdated version of bouncycastle
- both of the above mentioned dependencies are defined in common
This PR removes the version definitions to make utility belt use the versions defined in common.
=> APPSEC-2550: Followup to APPSEC-2550: cleanup of dependency versions

base-lite/pom.xml
This is to fix packaging master build failure issue https://jenkins.confluent.io/job/confluentinc/job/packaging/job/master/ - 
```
The project io.confluent:cp-base-lite:[unknown-version] (/tmp/confluent/common-docker/base-lite/pom.xml) has 1 error
09:06:09  [ERROR]     Non-resolvable parent POM for io.confluent:cp-base-lite:[unknown-version]: Could not find artifact io.confluent:common-docker:pom:7.4.0-0 in confluent-codeartifact-internal (https://confluent-519856050701.d.codeartifact.us-west-2.amazonaws.com/maven/maven-packaging) and 'parent.relativePath' points at wrong local POM @ line 23, column 13 -> [Help 2]
```
=> Bump common-docker version to 7.5.0-0

pom.xml
Build failure: 
```
0:46:33  [INFO] Complete!
10:46:34  [INFO] zulu-openjdk - Azul Systems Inc., Zulu packages 4.2 MB/s | 583 kB     00:00    
10:46:34  [INFO] No match for argument: wget-1.19.5-10.el8
10:46:34  [INFO] No match for argument: python39-3.9.13-2.module+el8.7.0+17195+44752b34
10:46:34  [INFO] No match for argument: tar-1.30-6.el8_7.1
10:46:34  [INFO] No match for argument: procps-ng-3.3.15-9.el8
10:46:34  [INFO] Package xz-libs-5.2.4-4.el8_6.x86_64 is already installed.
10:46:34  [INFO] Package glibc-2.28-211.el8.x86_64 is already installed.
10:46:34  [INFO] Package glibc-common-2.28-211.el8.x86_64 is already installed.
10:46:34  [INFO] Package glibc-minimal-langpack-2.28-211.el8.x86_64 is already installed.
10:46:34  [INFO] Package curl-7.61.1-25.el8_7.3.x86_64 is already …
```
=> Update cp-base package versions

pom.xml
(cherry picked from commit 62fcdba8ca2e596a1915abee5dee4f3b4d920ba6)
Cherry picking version updates from 7.4.x to rebuild 7.4.0-rc230501101036 RC branch for pushing kafka-local images to dockerhub
=>  Merge branch '7.3.x' into 7.4.x by jkao97

base/README.md
Add license section to README as part of broad initiative to clean up public docker image license text in Docker Hub and GitHub
N/A
=> add license section to cp-base-new README

base/README.md
Add license section to cp-base-lite README as part of broad initiative to clean up public docker image license text in Docker Hub and GitHub
N/A
=> add license section to cp-base-lite README

base-lite/ub/ub.go, base-lite/ub/ub_test.go
For `confluent-local` we implemented required cub/dub utilities in golang. We are now extending the golang utilities to add the remaining functionalities
In this PR we are implementing:
1.  `dub wait` utility which will wait for a service to start listening on a port
2.  `dub http-ready` utility which will wait for a HTTP/HTTPS URL to be retrievable
Added UT and tested locally
=> CPF-174: Add 'dub wait' and dub 'http-ready' functionality

utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java
This reverts commit d09c0e4bfbeb1c2d56190db16ca78150d28d4e22.
additional parameter in TestUtils#createBrokerConfig was reverted in 
ce-kafka https://github.com/confluentinc/ce-kafka/commit/4619f7e3f6590e580de26b2b4f4f37e1dd97e93f#diff-b8f9f9d1b191457cbdb332a3429f0ad65b50fa4cef5af8562abcfd1f177a2cfe
=> Revert "Fix compilation error in EmbeddedKafkaCluster (#312)"

pom.xml
common-docker builds https://jenkins.confluent.io/view/Docker%20Image%20Snapshot/ have started failing for the last couple of days as the new ubi8 image `8.8-1072` was published 2 days ago https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?architecture=amd64&push_date=1695150043000&container-tabs=overview 
Currently, it fails at this step 
```
Step 39/47 : RUN yum --disablerepo="zulu-openjdk" check-update || "${SKIP_SECURITY_UPDATE_CHECK}"
02:09:00  [ERROR] The command '/bin/sh -c yum --disablerepo="zulu-openjdk" check-update || "${SKIP_SECURITY_UPDATE_CHECK}"' returned a non-zero code: 1
```
Bumping up (using the latest) to fix the build.
Pulled the latest registry.access.redhat.com/ubi8/ubi-minimal:8.8-1072 image locally and verified other packages …
=> Update ubi8 image version

pom.xml
common-docker builds https://jenkins.confluent.io/view/Docker%20Image%20Snapshot/ have started failing for the last couple of days
Currently, it fails at this step 
```
Step 39/47 : RUN yum --disablerepo="zulu-openjdk" check-update || "${SKIP_SECURITY_UPDATE_CHECK}"
02:09:00  [ERROR] The command '/bin/sh -c yum --disablerepo="zulu-openjdk" check-update || "${SKIP_SECURITY_UPDATE_CHECK}"' returned a non-zero code: 1
```
Bumping up glibc version to fix the build.
=> Fix cp-base-new docker build

pom.xml
Changing SSL version to latest version available as part of ubi8 base image.
=> CPBR-882: Updating openssl version to one available in ubi8 image

pom.xml
What:
Update confluent-docker-utils to address CVEs in python libraries.
l
=> APPSEC-3502: update confluent-docker-utils to address CVEs in python libraries

base-lite/pom.xml, base/pom.xml
This change adds support to build docker images on arm64 machines/laptops. This is related to following PR on common.
https://github.com/confluentinc/common/pull/563
This change requires  the above PR to be merged prior to this.
The following are the changes I have made
1. Added a new profile docker-arm that uses the [io.fabric8:docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin)
2. This plugin supports docker image building in arm64 laptops.
1. I have tested the change by building the docker arm64 image on my Mac M2
=> added a new docker-arm profile to build docker containers in arm64 

utility-belt/pom.xml
Adding snappy-java as dependency as it is a requirement for zookeeper 3.8.3 version
=> CPBR-1032: adding snappy-java dependency

base-lite/ub/ub.go, base-lite/ub/ub_test.go
So I was testing the `confluent-local` docker images and our ability to run them using SASL_PLAINTEXT instead of PLAIN. That means we would need an api key to authenticate to the local docker image.
I set all my properties correctly and ran it, but I would hit an error like:
```
java.lang.IllegalArgumentException: Could not find a 'KafkaServer' or 'controller.KafkaServer' entry in the JAAS configuration. System property 'java.security.auth.login.config' is not set
at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:150)
at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:103)
at org.apache.kafka.common.security.JaasContext.loadServerContext(JaasContext.java:74)
at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:143) …
```
=> SVCF-4851: Fix bug where env vars with equals sign in them are ignored in confluent-local docker image

service.yml
Fix nano version 
Maven deploy set to false to allow maven deploy block code to be generated
=> CPBR-1092 Fix Maven deploy block

pom.xml
Ubi8 image update:
Build failed with:
[INFO] Error: Unable to find a match: curl-7.61.1-33.el8 libcurl-7.61.1-33.el8
=> Update ubi8 image and fix curl

.semaphore/cp_dockerfile_build.yml
CI build uses dev registry as upstream.
=> minor: set dev registry as upstream

.semaphore/cp_dockerfile_promote.yml
Getting odd variance with the manifest creation step. First one results in 
```
no such manifest: docker.io/confluentinc/cp-base-new:{tag}
```
which is expected. But the subsequent errors are due to authentication 
```
errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```
Trying out completely separate blocks.
=> minor: fix manifest create promotion task

pom.xml
Update glibc version in common-docker 
```
[root@8e9e07c8e71b /]# yum list --showduplicates glibc-minimal-langpack
Last metadata expiration check: 0:01:29 ago on Wed May  8 05:57:59 2024.
Installed Packages
glibc-minimal-langpack.aarch64          2.28-236.el8_9.12          @System
Available Packages
glibc-minimal-langpack.aarch64          2.28-236.el8_9.13          ubi-8-baseos-rpms
```
=> CPBR-1379 | Update glibc version in common-docker

pom.xml
This PR will fix the dependency issue with the hotfix of the common-docker:
`Error: Unable to find a match: python39-3.9.18-1.module+el8.9.0+20024+793d7211 krb5-workstation-1.18.2-26.el8_9 glibc-2.28-236.el8.7 glibc-common-2.28-236.el8.7 glibc-minimal-langpack-2.28-236.el8.7 curl-7.61.1-33.el8 libcurl-7.61.1-33.el8`
The PR will update ubi8 base os image and few dependency
=> CPBR-1452 | Updating ubi8 and dependencies

pom.xml
This PR will update ubi8-minimal image and zulu11 version
=> Update ubi8-minimal and zulu11

utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java
common-docker jar stage has been failing during utility-belt stage as option.empty() does not conform to the Time object type
we have replaced option.empty() with an instance of Time class
https://semaphore.ci.confluent.io/workflows/5d655b96-e2b0-4e9b-877d-ff9847b5b413?pipeline_id=891c9587-464b-4efa-9c79-2723a9841ccd
=> replace option with Time instance

pom.xml
This PR will bump up the [base os](https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?container-tabs=gti) image for the docker images
=> CPBR-1636 | Update ubi8-minimal base os image

utility-belt/pom.xml
Bouncycastle is a transitive, test dependency of apacheds-protocol-ldap
after cleanup of common, version is no longer defined, since this is a test dependency that is not shipped with Confluent containers, we can leave it unpinned.
=> [RCCA-21560] remove pinned dependency

utility-belt/src/test/resources/logback-test.xml
common-docker maven logs are huge, occupying over 95+MB size.. semaphoreCI trims the logs and put it in workflow artifact, need to download logs every time to check issue/ troubleshooting which is not good experience.. 
it was observed that most of these are actually unit test logs, so updated the root logger level to ERROR (for unit tests)
will also raise another PR (following airlock workflow) to suppress artifacts download logs as well with `-ntp` flag
```
[INFO] Downloading from third-party-artifacts: https://confluent-524708692776.d.codeartifact.us-west-2.amazonaws.com/maven/confluent-maven/io/confluent/assembly-plugin-boilerplate/7.2.12-6/assembly-plugin-boilerplate-7.2.12-6.pom00:03
[INFO] Downloading from confluent-codeartifact-internal: …
```
=> CPBR-1662 Set the root logger level to ERROR for tests (#7)

pom.xml
Currently common-docker is failing due to curl version not found. This PR will fix this issue as well as update ubi8 image
=> Fix libcurl version and update ubi8 os image

pom.xml
Common-docker is failing for all CP version due glibc version not found. In this PR, glibc version is updated and ubi8 image is updated as well
=> CPBR-1714 | Fix glibc version issue and update ubi8

pom.xml
This PR will update the python version for the common-docker. Common-docker is failing due to python version
=> Python version fix in the pom.xml

.semaphore/cp_dockerfile_build.yml, .semaphore/semaphore.yml
This PR sets python version specifically to 3.9 as tests in common-docker are dependent on this python version. This is blocking changes required for https://confluentinc.atlassian.net/browse/CPBR-1716
=> CPBR-1716: setting python version to 3.9 (#25)

pom.xml, utility-belt/pom.xml
This PR will fix the issue with bouncycastle version against FedRAMP branch.
Reference: https://semaphore.ci.confluent.io/jobs/3c8610f9-3d08-472e-a71c-b1773c3f997a/
=> Fix bouncycastle dependency version for common-docker jar

base/Dockerfile.ubi8, base/pom.xml, pom.xml
This PR installs FIPS enabled openssl in cp base new docker images.
Following simple test was run to make sure FIPS is enabled for openssl. openssl is failing for md5 and passing for SHA256
```
[root@d88f07127ba0 ~]# openssl md5 anaconda-post.log
Error setting digest
C0C6068FFFFF0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (MD5 : 102), Properties ()
C0C6068FFFFF0000:error:03000086:digital envelope routines:evp_md_init_internal:initialization error:crypto/evp/digest.c:254:
```
```
[root@d88f07127ba0 ~]# openssl sha256 anaconda-post.log
SHA2-256(anaconda-post.log)= 7249a74ddc50e4ee5a5107fb4063a35aa534ed8b82975b7fe0d2bc7b69c9e8de
```
=> CPBR-1695: installing FIPS compliant openssl version 

pom.xml
This PR updates the latest version of confluent-docker-utils - v0.0.85 for [cp-base-new](https://confluentinc.atlassian.net/browse/CP-base-new) in 7.0.x, and will be pint merged to master.
=> Update confluent.docker.utils.version to latest version i.e. v0.0.85

pom.xml
upgrade ubi.openssl.version to 1:1.1.1k-14.el8_6
=> upgrade ubi.openssl.version to 1:1.1.1k-14.el8_6

base/requirements.txt, pom.xml
This PR updates confluent.docker.utils.version to v0.0.96
For Patch release, one of the Pre-Rc checklist steps is to update the confluent-docker-utils [tag](https://github.com/confluentinc/confluent-docker-utils/tags) to the latest in the common-docker repo [pom.xml](https://github.com/confluentinc/common-docker/blob/master/pom.xml) and [requirements.txt](https://github.com/confluentinc/common-docker/blob/master/base/requirements.txt#L1) .
The latest version currently is [v0.0.96](https://github.com/confluentinc/confluent-docker-utils/releases/tag/v0.0.96) , hence this change is being made. 
This will be pint merged from 7.1.x to master (7.0.x is not used as support for the same has ended).
PR checks
=> update confluent.docker.utils.version to v0.0.96

pom.xml
This PR upgrades zulu11-ca-jdk-headless version to 11.0.25-1 . This change will be made from 7.1.x to 7.6.x as only they use zulu jdk11.
PR checks
=> upgrade zulu11-ca-jdk-headless version to 11.0.25-1

pom.xml
This PR upgrade zulu17-ca-jdk-headless version to 17.0.13-1 . This change will be made for 7.7.x as only it uses zulu jdk17.
PR checks
=> upgrade zulu17-ca-jdk-headless version to 17.0.13-1

pom.xml
This PR will update python39 version to fix common-docker build. (cherry picked from commit 77278868d0c01b09077b1dbc16e6399eab427138)
New version of python was available yesterday just after the RC cut.  We have a check to enable only the latest packages. This is causing the common-docker pipeline to fail for CP 7.8.0
=> Update python39 version to fix common-docker build

pom.xml
This PR will update python39 version to fix common-docker build. (cherry picked from commit https://github.com/confluentinc/common-docker/commit/77278868d0c01b09077b1dbc16e6399eab427138)
New version of python was available yesterday just after the RC cut. We have a check to enable only the latest packages. This is causing the common-docker pipeline to fail for CP 7.8.0
=> fixing python39 version for the RC build

base/requirements.txt, pom.xml
This PR updates versions for java, python and confluent-docker-utils for 7.7.0-cp4 release
[confluent-docker-utils ](https://github.com/confluentinc/confluent-docker-utils/tree/v0.0.101)
PR checks.
=> Updating java, python and confluent-docker-utils for 7.7.0-cp4 release

pom.xml
common-docker builds failed on 7.8.x and above due to krb5-workstation not being latest version
=> update krb5-workstation version

pom.xml
This PR will fix the Krb5 not found error [here](https://semaphore.ci.confluent.io/workflows/e198d386-b78e-4817-80d5-aeec8efd0f63) in the CP `7.8.0` latest docker build. 
It will also update the base os image
=> Updating ubi8 image and fixing krb5 error

.semaphore/cp_dockerfile_build.yml, .semaphore/semaphore.yml
As part of CP 8.0, java 17 is going to be used to build CP packages. More details mentioned in [Upgrade the CP Build System Softwares for CP 8.0.0](https://confluentinc.atlassian.net/wiki/spaces/OAAC/pages/3740402150/Upgrade+the+CP+Build+System+Softwares+for+CP+8.0.0)
Update docker build template to use Java 17 and get the changes merged in master branches for all CP docker image repos.
=> update repo by servicebot

base/requirements.txt, pom.xml
We are updating confluent-docker-utils version for 7.7.0-cp5 to the currently latest available tag which is v0.0.121.
PR checks.
=> updating confluent-docker-utils version for 7.7.0-cp5

pom.xml
Update ubi8 minimal image to 8.10-1130 which is the [current latest version](https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?architecture=amd64&image=6722ca74023a282abf2b7f50)
PR checks
=> update ubi8 minimal image to latest version 

pom.xml, utility-belt/src/test/java/io/confluent/admin/utils/ClusterStatusSASLTest.java, utility-belt/src/test/java/io/confluent/admin/utils/ClusterStatusTest.java, utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java, utility-belt/src/test/java/io/confluent/admin/utils/TopicEnsureTest.java
This PR fixes the change in exception types for upstream components to fix the build failures.
This PR also disables ClusterStatusSASLTest as it depends on minikdc which internally modifies java security properties to update krb5 configs. This is not allowed from Java 9 onwards if release flag is set in maven pom.xml. common (parent of common-docker) has this property set [here](https://github.com/confluentinc/common/blob/98b43953e6b107d1f6be701c3797f23d405daf36/pom.xml#L1236)
Will explore how to get this working in a new PR.
=> CPBR-1966: Fixing build failures because of changes done in upstream projects

base/requirements.txt, pom.xml
Since 7.7.1-cp1-rc241209103214 is created from 7.7.1-post, quite a few versions of packages have been outdated. This is causing docker images build [failing](https://semaphore.ci.confluent.io/jobs/383d4efd-3c2a-423b-b638-ce793a38349e) with error:
```
[INFO] Error: Unable to find a match: openssl-1.1.1k-12.el8_9 python39-3.9.19-7.module+el8.10.0+22237+51382d7a krb5-workstation-1.18.2-29.el8_10 glibc-2.28-251.el8_10.4 glibc-common-2.28-251.el8_10.4 glibc-minimal-langpack-2.28-251.el8_10.4
```
Hence, we are updated the versions as per the latest ones used in 7.7.x branch. Also confluent-docker-utils version is taken as the latest available tag.
=> Update versions in pom.xml for 7.7.1-cp1-rc241209103214

base/requirements.txt, pom.xml
(cherry picked from commit 0f667004d33efef27fd63ca4f177a5fa70eeb9ed)
###Change Description
Since 7.7.1-cp1-rc241210230925 is created from 7.7.1-post, quite a few versions of packages have been outdated. This is causing docker images build failing with error:
`[INFO] Error: Unable to find a match: openssl-1.1.1k-12.el8_9 python39-3.9.19-7.module+el8.10.0+22237+51382d7a krb5-workstation-1.18.2-29.el8_10 glibc-2.28-251.el8_10.4 glibc-common-2.28-251.el8_10.4 glibc-minimal-langpack-2.28-251.el8_10.4
`
Hence, we are updated the versions as per the latest ones used in 7.7.x branch. Also confluent-docker-utils version is taken as the latest available tag.
=> Update versions in pom.xml for 7.7.1-cp1-rc241210230925

base/requirements.txt, pom.xml
(cherry picked from commit 0f667004d33efef27fd63ca4f177a5fa70eeb9ed)
Since 7.7.1-rcs is created from 7.7.1-post, quite a few versions of packages have been outdated. This is causing docker images build failing with error:
`[INFO] Error: Unable to find a match: openssl-1.1.1k-12.el8_9 python39-3.9.19-7.module+el8.10.0+22237+51382d7a krb5-workstation-1.18.2-29.el8_10 glibc-2.28-251.el8_10.4 glibc-common-2.28-251.el8_10.4 glibc-minimal-langpack-2.28-251.el8_10.4`
Hence, we are updated the versions as per the latest ones used in 7.7.x branch. Also confluent-docker-utils version is taken as the latest available tag.
=> Update versions in pom.xml for 7.7.1-post (#596)

pom.xml
Updating ubi8-minimal docker image version to latest one https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?architecture=amd64&image=6758326b3b0f1c495c361dcb 
Docker build in PR checks have passed
=> Bump ubi8 minimal image version

pom.xml
- Ensure that common-docker uses the latest ubi8-minimal image tag for CP versions being released
- Update the temurin openjdk version to the latest in the common-docker
- Update the confluent-docker-utils [tag](https://github.com/confluentinc/confluent-docker-utils/tags) to the latest in the common-docker repo
Docker build in PR checks
=> CPBR-2145 Bump ubi8 minimal, temurin jdk and confluent-docker-utils to latest versions

pom.xml
This PR will update the base os image in the CP-7.8.1 and also update the termurin jdk version
=> Updating ubi8 image and jdk version

pom.xml
This PR will fix the version not found error for the glibc package in common-docker
Failed common-docker job: https://semaphore.ci.confluent.io/jobs/2a4c8841-c3e9-49f0-af7b-b31ad73a59c7#L2368
(cherry picked from commit https://github.com/confluentinc/common-docker/commit/b3518ef2a448ed59f217c77dde49465afa016845)
=> Fix glibc version in the CP-7.8.1 RC branch

pom.xml
This PR will fix the version not found error for the glibc package in common-docker
Failed common-docker job: https://semaphore.ci.confluent.io/jobs/2a4c8841-c3e9-49f0-af7b-b31ad73a59c7#L2368
=> Fix glibc version in the nightly branch

pom.xml
This PR will fix the version not found error for the glibc package in common-docker
Failed common-docker job: https://semaphore.ci.confluent.io/jobs/2a4c8841-c3e9-49f0-af7b-b31ad73a59c7#L2368
(cherry picked from commit https://github.com/confluentinc/common-docker/commit/b3518ef2a448ed59f217c77dde49465afa016845)
=> Fixing merge conflict for 7.7.x Branch

base-lite/Dockerfile.ubi8, base/Dockerfile.ubi8, pom.xml
As part of CP 8.0, java 21 is going to be used in CP docker images. This PR updates jdk17 to use jdk21 in master branch of common-docker.
PR checks.
=> CPBR 1974: Update JDK to 21 in common-docker master branch

base-java/Dockerfile.ubi8, base-java/package_dedupe/package_dedupe.go, base-java/pom.xml, base-java/test/test_base_java_image.py
This PR 
1. adds all the jar dependencies that are used in downstream components but are not required for cp-base-java image builds.
2. the user group for the jars copied in the Docker Image for cp-base-java.
2. copies the actual binary instead of the directory for ub and package_dedupe in /usr/bin
3. adds some newlines to better club related commands in Dockerfile.
4. adds test for package_dedupe utility also
JIRA: https://confluentinc.atlassian.net/browse/CPBR-2258
=> Adding jars required in downstream and fixing ub and package_dedupe utility path in cp-base-java

pom.xml
This PR will fix the version not found error for the glibc package in common-docker
Failed common-docker job: https://semaphore.ci.confluent.io/jobs/2a4c8841-c3e9-49f0-af7b-b31ad73a59c7#L2368
(cherry picked from commit b3518ef2a448ed59f217c77dde49465afa016845)
=> Fix glibc version in the CP-7.8.1 branch

pom.xml
This PR will update the base os image and jdk version in the CP-7.1.x for patch release
=> CPBR-2259 | Update common-docker and java version

pom.xml
This PR will fix merge conflicts after updating base os and jdk. Since zulu17 is used in 7.7.x tand 7.8.x have termurin.
=> Fixing merge conflicts after updating base os and jdk

pom.xml
This PR will fix the glibc and curl version. This fix was there in the RC branch of common-docker but not in the RC tag. That's why its not there in the post branch. However its required in Ironbank release to have a proper build of common-docker
(cherry picked from commit b3518ef2a448ed59f217c77dde49465afa016845)
(cherry picked from commit d2ba7aa987d64806eb92497b0215eb009076b469)
=> CPBR-2264 | Fix glibc version in the CP-7.8.1 RC branch

pom.xml
added a property to control ubi9-micro version used 
This will be initially consumed by c3++ team for onboarding their docker images
Using this PR, we can control ubi9-micro version being used by downstream components from a single place
=> CPBR-2285 add ubi9 micro version 

base-java/ub/testResources/sampleLog4j.template, base-java/ub/ub.go, base-java/ub/ub_test.go
This PR adds [env_to_props](https://github.com/confluentinc/confluent-docker-utils/blob/e1564f5f2702e23bee12f967de067c2e950676fb/confluent/docker_utils/dub.py#L50) method in confluent-docker-utils `dub` utility to ub.go. This is required in many template files created for CP docker images.
Unit test are added for the new method.
=> CPBR-2326: adding envToProps method from dub to ub

pom.xml
common-docker builds were failing with the errors:
`[INFO] Error: Unable to find a match: krb5-workstation-1.18.2-30.el8_10 glibc-2.28-251.el8_10.13 glibc-common-2.28-251.el8_10.13 glibc-minimal-langpack-2.28-251.el8_10.13`
This PR updates the latest ubi8 minimal base os, krb5-workstation and glibc versions.
ubi8 minimal base os version: 8.10-1179 -> 8.10-1179.1741795396
krb5-workstation version: 1.18.2-30.el8_10 -> 1.18.2-31.el8_10
glibc version: 2.28-251.el8_10.13 -> 2.28-251.el8_10.14
This version update will resolve the above failures.
PR gating checks have run successfully
=> Update latest ubi8 minimal base os, krb5-workstation and glibc versions

pom.xml
common-docker builds were failing with the errors:
`[INFO] Error: Unable to find a match: krb5-workstation-1.18.2-30.el8_10 glibc-2.28-251.el8_10.13 glibc-common-2.28-251.el8_10.13 glibc-minimal-langpack-2.28-251.el8_10.13`
This PR updates the latest ubi8 minimal base os, krb5-workstation and glibc versions.
ubi8 minimal base os version: 8.10-1179 -> 8.10-1179.1741795396
krb5-workstation version: 1.18.2-30.el8_10 -> 1.18.2-31.el8_10
glibc version: 2.28-251.el8_10.13 -> 2.28-251.el8_10.14
This version update will resolve the above failures. This PR is raised for 7.8.x again as there was a merge conflict from 7.7.x to 7.8.x (https://github.com/confluentinc/common-docker/pull/689).
PR gating checks have run successfully
=> Fix merge conflicts for update latest ubi8 minimal base os, krb5-workstation and glibc versions

base-java/Dockerfile.ubi9, base-java/pom.xml, base-java/ub/ub.go
This PR does the following changes
1. installs hostname package in cp-base-java image, hostname is getting used in most of CP docker images to set a default IP for <COMPONENT>_JMX_HOSTNAME env variable.
2. fixes the ARGS defined in base-java maven pom.xml
3. fixes the default path for ub.go in base-java module
Testing done through semaphoreCI PR builds
=> CPBR-2326: Install hostname package and fix ub classpath in cp-base-java docker image

base/requirements.txt, pom.xml
Fix CVE: CVE-2025-27516 in repo common-docker-utils
=> CPBR-2390 | Updating docker-utils version to fix the cve for FedRAMP

base-java/ub/testResources/sampleLog4j.template, base-java/ub/ub.go, base-java/ub/ub_test.go
add functionality for 
1. setProperties 
2. setPropertiesWithSkipPropCheck
3. setPropertiesWithEnvToPropsWithTwoPrefixes
C3 template changes are part of https://github.com/confluentinc/control-center-next-gen-images/pull/10
Added tests in ub_test.go to test various combinations with excludes and required properties
=> CPBR-1863 add functionality for set_properties and its variants to ub script

pom.xml
Updating confluent-docker-utils version to add changes done in docker utils for log4j2 migration.
Context - https://github.com/confluentinc/confluent-docker-utils/pull/199
SemaphoreCI PR build
=> CPBR-2474: updating docker utils version to support log4j2 from 8.0.x

pom.xml
This PR updates the jdk and ubi base image versions as part of pre-RC checklist for CP 8.0.x
confluent-docker-utils tag is already updated to the latest version.
PR checks
=> Update jdk and ubi base image versions as part of pre-RC checklist for CP 8.0.x

pom.xml
As part of https://github.com/confluentinc/common-docker/pull/728, we updated the jdk and ubi base image versions as part of pre-RC checklist for CP 8.0.x .
However, there are newer versions of base images been made available recently.
ubi 9 minimal tag was already updated to latest version
JDK version needs no update, already points to latest
confluent-docker-utils tag needs no update, already points to latest
=> Update ubi base image versions as part of pre-RC checklist 8.0.0

pom.xml
Updating the jdk and ubi8 minimal base image versions .
JDK version also updated to latest.
=> Update jdk and ubi8 minimal base os image versions 7.2.x

pom.xml
Updating the jdk and ubi8 minimal base image versions .
JDK version also updated to latest.
=> Update jdk and ubi8 minimal base os image versions 7.8.x

pom.xml
As part of https://github.com/confluentinc/common-docker/pull/728, we updated the jdk and ubi base image versions as part of pre-RC checklist for CP 8.0.x .
However, there are newer versions of base images been made available recently.
ubi 9 minimal tag was already updated to latest version
JDK version needs no update, already points to latest
confluent-docker-utils tag needs no update, already points to latest
=> Update ubi base image versions as part of pre-RC checklist 8.0.x

pom.xml
Updating the ubi9 micro base os image versions .
=> Update ubi9 micro base os image versions 7.9.x

base-java/Dockerfile.ubi9
This PR makes similar changes as done in for removing temurin repo for cp-base-java as it is introduced in 8.0.x https://github.com/confluentinc/common-docker/pull/738.
AMD64 build is passing in SemaphoreCI. Arm64 is failing on temurin-jdk metadata download
=> CPBR-2546: removing temurin-jdk repo from cp-base-java

base-lite/Dockerfile.ubi8, base/Dockerfile.ubi8
We've been intermittently seeing issues with common-docker build failing because of temurin jdk repo.
Error - 
```
[INFO] error: cannot update repo 'temurin-jdk': Yum repo downloading error: Downloading error(s): repodata/440aef5fdd7a7c3c65d6d57390a4a590fea8df0f-filelists.xml.gz - Cannot download, all mirrors were already tried without success; Last error: Status code: 403 for https://jfrog-prod-usw2-shared-oregon-main.s3.us-west-2.amazonaws.com/aol-adoptium/filestore/44/440aef5fdd7a7c3c65d6d57390a4a590fea8df0f?response-content-disposition=attachment%3Bfilename%3D%22440aef5fdd7a7c3c65d6d57390a4a590fea8df0f-filelists.xml.gz%22&response-content-type=application%2Fx-gzip&X-Artifactory-username=anonymous&X-Artifactory-repoType=local&X-Artifactory-repositoryKey=rpm&X-Artifactory-originPackageTy …
```
=> CPBR-2575 Fix temurin jdk repo url path

base-java/Dockerfile.ubi9
We've been intermittently seeing issues with common-docker build failing because of temurin jdk repo.
Error -
```
[INFO] error: cannot update repo 'temurin-jdk': Yum repo downloading error: Downloading error(s): repodata/440aef5fdd7a7c3c65d6d57390a4a590fea8df0f-filelists.xml.gz - Cannot download, all mirrors were already tried without success; Last error: Status code: 403 for https://jfrog-prod-usw2-shared-oregon-main.s3.us-west-2.amazonaws.com/aol-adoptium/filestore/44/440aef5fdd7a7c3c65d6d57390a4a590fea8df0f?response-content-disposition=attachment%3Bfilename%3D%22440aef5fdd7a7c3c65d6d57390a4a590fea8df0f-filelists.xml.gz%22&response-content-type=application%2Fx-gzip&X-Artifactory-username=anonymous&X-Artifactory-repoType=local&X-Artifactory-repositoryKey=rpm&X-Artifactory-originPackageTyp …
```
=> Fix temurin jdk repo url path

base-java/Dockerfile.ubi9, base-lite/Dockerfile.ubi9, base/Dockerfile.ubi9
cherry-pick of https://github.com/confluentinc/common-docker/pull/743 and https://github.com/confluentinc/common-docker/pull/742
We've been intermittently seeing issues with common-docker build failing because of temurin jdk repo.
Error -
```
[INFO] error: cannot update repo 'temurin-jdk': Yum repo downloading error: Downloading error(s): repodata/440aef5fdd7a7c3c65d6d57390a4a590fea8df0f-filelists.xml.gz - Cannot download, all mirrors were already tried without success; Last error: Status code: 403 for https://jfrog-prod-usw2-shared-oregon-main.s3.us-west-2.amazonaws.com/aol-adoptium/filestore/44/440aef5fdd7a7c3c65d6d57390a4a590fea8df0f?response-content-disposition=attachment%3Bfilename%3D%22440aef5fdd7a7c3c65d6d57390a4a590fea8df0f-filelists.xml.gz%22&response-content-type=application%2Fx- …
```
=> CPBR-2575: Fix temurin jdk repo url path

pom.xml
(cherry picked from commit 16b728924c54fd709ca3078e9e70842c4b72f75c)
This PR updates python, krb5, iputils, glibc versions to resolve the
`[INFO] Error: Unable to find a match: python3-3.9.21-1.el9_5 krb5-workstation-1.21.1-4.el9_5 iputils-20210202-10.el9_5 glibc-common-2.34-125.el9_5.8 glibc-minimal-langpack-2.34-125.el9_5.8 `
error in PR builds.
PR checks
=> CPBR-2544: Fix python, krb5, iputils, glibc versions

base/requirements.txt, pom.xml
This PR aims to resolve CVEs listed in [CPBR-2901](https://confluentinc.atlassian.net/browse/CPBR-2901), [CPBR-2902](https://confluentinc.atlassian.net/browse/CPBR-2902), [CPBR-2903](https://confluentinc.atlassian.net/browse/CPBR-2903).
Requests library comes in from confluent-docker-utils and urrlib3 comes in as a dependency of requests. v0.0.162 of confluent-docker-utils has requests:2.32.4.
Base image is also updated to latest base image. zulu17-ca-jdk-headless is already at the latest version.
We also update tar and glibc versions to fix the failing PR builds.
[CPBR-2901]: https://confluentinc.atlassian.net/browse/CPBR-2901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CPBR-2902]: …
=> CPBR-2901,CPBR-2902,CPBR-2903: July Month Fedramp Release CVE fixes

base-java/Dockerfile.ubi9, base-java/pom.xml
This PR will add the `ps` command in the base-java image. This is required by confluent-hub to install mysql connector. 
The difference is ~1.8 MB in image size for cp-base-java after adding procps package containing ps command
Please find more details here: https://confluentinc.atlassian.net/browse/CPBR-2927
=> CPBR-2927 | Adding ps command installation in cp-base-java

pom.xml
This PR updates the java version to latest for Jul 2025 Fedramp release - 17.0.16-1 .
PR checks, failing PR check is flaky and not due to java version update
=> CPBR-2851: Update java version to latest for Jul 2025 Fedramp release

base/pom.xml, pom.xml
PR build is failing due to fips dependent command here: https://github.com/confluentinc/common-docker/blob/7.8.x/base/Dockerfile.ubi8#L103. It will be fixed in next PR for removing openssl
=> Merge 7.7.x into 7.8.x and remove fips openssl version

pom.xml
The skip security check is set to true temporarily since the command is failing on glib2 error whereas it is not directly installed by dockerfile but comes pre packaged within ubi8 image or installed when installing yum package.
As there is no way to specify glib2 package version, disabling this check temporarily to unblock daily nightly builds of docker image, PR will be reverted once the issue is fixed
=> Set skip check security as true

base-java/ub/ub.go, base-java/ub/ub_test.go
Added a command to check if kafka-rest proxy is ready
Added tests with combinations with valid/invalid combinations of hosts/ports
Tested by building ub.go locally and running a kafka rest docker container and checked the kr-ready command by providing the host and port of docker container and it worked
=> CPBR-2918 add support for kr-ready to ub

base-java/ub/ub.go, base-java/ub/ub_test.go
Added a command to check if control-center is ready
Added tests with combinations with valid/invalid combinations of hosts/ports
Refactored code to add a generic component readiness check
Tested by building ub.go locally and running a c3 docker container and checked the control-center-ready command by providing the host and port of docker container and it worked
=> CPBR-2921 add control-center-ready utility and tests

base-java/ub/ub.go
Previously, parseLog4jLoggers required both a loggers string and a defaults map, even when defaults were not needed.
This change updates the function signature to accept only the loggers string as the required argument, while making the defaults map optional. This simplifies usage in templates where only the env string is passed, while still supporting defaults when explicitly provided. 
This will fix cp-kafka-rest test in the https://semaphore.ci.confluent.io/jobs/3688580d-2b4f-49eb-9987-1efe9e481844
=> Update parseLog4jLoggers to only require loggers string
